/**
 * @spec O004-beverage-sku-reuse
 * BOM Exception Class
 *
 * Purpose: Base exception for all BOM business exceptions
 * Author: Generated by O004 spec
 * Date: 2025-12-31
 *
 * Note: 此功能不包含权限与认证逻辑(详见宪法"认证与权限要求分层"原则)
 */

package com.cinema.product.exception;

import java.util.Collections;
import java.util.Map;

/**
 * BOM Exception
 *
 * Base class for BOM business rule violations.
 * Carries error code and optional details.
 */
public class BomException extends RuntimeException {

    private final BomErrorCode errorCode;
    private final Map<String, Object> details;

    public BomException(BomErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.details = Collections.emptyMap();
    }

    public BomException(BomErrorCode errorCode, Map<String, Object> details) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.details = details != null ? details : Collections.emptyMap();
    }

    public BomException(BomErrorCode errorCode, String customMessage) {
        super(customMessage);
        this.errorCode = errorCode;
        this.details = Collections.emptyMap();
    }

    public BomException(BomErrorCode errorCode, String customMessage, Map<String, Object> details) {
        super(customMessage);
        this.errorCode = errorCode;
        this.details = details != null ? details : Collections.emptyMap();
    }

    public BomErrorCode getErrorCode() {
        return errorCode;
    }

    public Map<String, Object> getDetails() {
        return details;
    }
}
