/**
 * @spec O004-beverage-sku-reuse
 * BOM Error Code Enumeration
 *
 * Purpose: Standardized error codes for BOM operations
 * Format: <MODULE>_<CATEGORY>_<NUMBER>
 *   - MODULE: BOM (Bill of Materials)
 *   - CATEGORY: VAL (Validation), NTF (Not Found), DUP (Duplicate), BIZ (Business Rule), SYS (System Error)
 *   - NUMBER: 3-digit sequence (001-999)
 *
 * Author: Generated by O004 spec
 * Date: 2025-12-31
 *
 * Note: 此功能不包含权限与认证逻辑(详见宪法"认证与权限要求分层"原则)
 */

package com.cinema.product.exception;

import org.springframework.http.HttpStatus;

/**
 * BOM Error Codes
 *
 * All error codes follow the format: BOM_<CATEGORY>_<NUMBER>
 */
public enum BomErrorCode {

    // ========== Validation Errors (VAL) - HTTP 400 ==========
    BOM_VAL_001("BOM配方只能为成品类型SKU创建，当前SKU类型为: %s", HttpStatus.BAD_REQUEST),
    BOM_VAL_002("BOM组件不能为空", HttpStatus.BAD_REQUEST),
    BOM_VAL_003("BOM组件数量必须大于0", HttpStatus.BAD_REQUEST),
    BOM_VAL_004("损耗率必须在0-1之间", HttpStatus.BAD_REQUEST),
    BOM_VAL_005("BOM组件不能包含成品本身（循环依赖）", HttpStatus.BAD_REQUEST),

    // ========== Not Found Errors (NTF) - HTTP 404 ==========
    BOM_NTF_001("BOM配方不存在: finishedProductId=%s", HttpStatus.NOT_FOUND),
    BOM_NTF_002("BOM组件SKU不存在: componentId=%s", HttpStatus.NOT_FOUND),

    // ========== Conflict Errors (DUP) - HTTP 409 ==========
    BOM_DUP_001("BOM配方已存在，请使用更新接口", HttpStatus.CONFLICT),

    // ========== Business Rule Errors (BIZ) - HTTP 422 ==========
    BOM_BIZ_001("BOM深度超过最大限制（3层）", HttpStatus.UNPROCESSABLE_ENTITY),
    BOM_BIZ_002("检测到BOM循环依赖", HttpStatus.UNPROCESSABLE_ENTITY),

    // ========== System Errors (SYS) - HTTP 500 ==========
    BOM_SYS_001("BOM配方保存失败", HttpStatus.INTERNAL_SERVER_ERROR),
    BOM_SYS_002("BOM配方删除失败", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String message;
    private final HttpStatus httpStatus;

    BomErrorCode(String message, HttpStatus httpStatus) {
        this.message = message;
        this.httpStatus = httpStatus;
    }

    /**
     * Get error code (enum name)
     * @return Error code string (e.g., "BOM_VAL_001")
     */
    public String getCode() {
        return this.name();
    }

    /**
     * Get error message
     * @return Human-readable error message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Get HTTP status code
     * @return HTTP status for this error type
     */
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    /**
     * Format message with parameters
     * @param args Message parameters for String.format
     * @return Formatted message
     */
    public String formatMessage(Object... args) {
        return String.format(this.message, args);
    }
}
