/**
 * @spec T006-e2e-report-configurator
 * Integration test for HTML-only setup workflow
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdir, writeFile, rm, readFile } from 'fs/promises'
import { join } from 'path'
import { tmpdir } from 'os'
import { parseSkillOptions } from '@/options-parser'
import { buildDirectoryStructure, getRequiredDirectories } from '@/directory-builder'
import { createDirectories } from '@/directory-manager'
import { generateReporterArray, generateArtifactRetentionPolicy } from '@/config-generator'
import { updatePlaywrightConfig } from '@/config-updater'
import { updateGitignore } from '@/gitignore-updater'

describe('HTML-only Setup Integration', () => {
  let testDir: string
  let configPath: string
  let gitignorePath: string

  beforeEach(async () => {
    // Create temporary test directory
    testDir = join(tmpdir(), `e2e-test-${Date.now()}`)
    await mkdir(testDir, { recursive: true })

    configPath = join(testDir, 'playwright.config.ts')
    gitignorePath = join(testDir, '.gitignore')

    // Create minimal playwright.config.ts
    const minimalConfig = `import { defineConfig } from '@playwright/test'

export default defineConfig({
  testDir: './tests',
  reporter: [['list']],
  use: {
    screenshot: 'off',
    video: 'off',
    trace: 'off'
  }
})
`
    await writeFile(configPath, minimalConfig, 'utf-8')
  })

  afterEach(async () => {
    // Cleanup test directory
    try {
      await rm(testDir, { recursive: true, force: true })
    } catch {
      // Ignore cleanup errors
    }
  })

  it('should complete full HTML-only setup workflow', async () => {
    // Step 1: Parse options (HTML only, default settings)
    const options = parseSkillOptions({
      format: 'html'
    })

    expect(options).toEqual({
      format: 'html',
      output: 'reports/e2e',
      artifacts: 'on-failure'
    })

    // Step 2: Build directory structure
    const structure = buildDirectoryStructure(options.output)

    expect(structure.basePath).toBe('reports/e2e')
    expect(structure.htmlDir).toBe('reports/e2e/html')

    // Step 3: Get required directories
    const requiredDirs = getRequiredDirectories(structure, options.format)

    expect(requiredDirs).toEqual([
      'reports/e2e/html',
      'reports/e2e/artifacts',
      'reports/e2e/artifacts/screenshots',
      'reports/e2e/artifacts/videos',
      'reports/e2e/artifacts/traces'
    ])

    // Step 4: Create directories
    const absoluteDirs = requiredDirs.map((dir) => join(testDir, dir))
    const createResult = await createDirectories(absoluteDirs)

    expect(createResult.created.length).toBe(5)
    expect(createResult.alreadyExisted.length).toBe(0)
    expect(createResult.failed.length).toBe(0)

    // Step 5: Generate reporter array
    const reporters = generateReporterArray({
      html: structure.htmlDir
    })

    expect(reporters).toHaveLength(2) // HTML + list
    expect(reporters[0]).toEqual(['html', {
      outputFolder: 'reports/e2e/html',
      open: 'never'
    }])

    // Step 6: Generate artifact policy
    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    expect(artifactPolicy).toEqual({
      screenshot: 'only-on-failure',
      video: 'retain-on-failure',
      trace: 'on-first-retry'
    })

    // Step 7: Update Playwright config
    const updateResult = await updatePlaywrightConfig(
      configPath,
      reporters,
      artifactPolicy
    )

    expect(updateResult.success).toBe(true)
    expect(updateResult.updated).toBe(true)
    expect(updateResult.backupPath).toBeDefined()

    // Verify config was updated
    const updatedConfig = await readFile(configPath, 'utf-8')
    expect(updatedConfig).toContain("['html', { outputFolder: 'reports/e2e/html'")
    expect(updatedConfig).toContain("screenshot: 'only-on-failure'")
    expect(updatedConfig).toContain("video: 'retain-on-failure'")
    expect(updatedConfig).toContain("trace: 'on-first-retry'")

    // Step 8: Update gitignore
    const gitignoreResult = await updateGitignore(
      options.output,
      gitignorePath
    )

    expect(gitignoreResult.updated).toBe(true)
    expect(gitignoreResult.created).toBe(true)
    expect(gitignoreResult.entryPath).toBe('reports/e2e/')

    // Verify gitignore was created and contains entry
    const gitignoreContent = await readFile(gitignorePath, 'utf-8')
    expect(gitignoreContent).toContain('reports/e2e/')
    expect(gitignoreContent).toContain('# Test reports (generated by e2e-report-configurator)')
  })

  it('should handle idempotent setup (running twice)', async () => {
    // First run
    const options = parseSkillOptions({ format: 'html' })
    const structure = buildDirectoryStructure(options.output)
    const requiredDirs = getRequiredDirectories(structure, options.format)
    const absoluteDirs = requiredDirs.map((dir) => join(testDir, dir))

    const firstRun = await createDirectories(absoluteDirs)
    expect(firstRun.created.length).toBe(5)

    const reporters = generateReporterArray({ html: structure.htmlDir })
    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    await updatePlaywrightConfig(configPath, reporters, artifactPolicy)
    await updateGitignore(options.output, gitignorePath)

    // Second run (should be idempotent)
    const secondRun = await createDirectories(absoluteDirs)
    expect(secondRun.created.length).toBe(0) // All already existed
    expect(secondRun.alreadyExisted.length).toBe(5)

    const secondUpdate = await updatePlaywrightConfig(
      configPath,
      reporters,
      artifactPolicy
    )
    expect(secondUpdate.success).toBe(true)

    const secondGitignore = await updateGitignore(options.output, gitignorePath)
    expect(secondGitignore.updated).toBe(false)
    expect(secondGitignore.alreadyPresent).toBe(true)
  })

  it('should handle custom output directory', async () => {
    const options = parseSkillOptions({
      format: 'html',
      output: 'test-reports'
    })

    const structure = buildDirectoryStructure(options.output)
    expect(structure.basePath).toBe('test-reports')
    expect(structure.htmlDir).toBe('test-reports/html')

    const requiredDirs = getRequiredDirectories(structure, options.format)
    const absoluteDirs = requiredDirs.map((dir) => join(testDir, dir))

    await createDirectories(absoluteDirs)

    const reporters = generateReporterArray({ html: structure.htmlDir })
    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    await updatePlaywrightConfig(configPath, reporters, artifactPolicy)

    const updatedConfig = await readFile(configPath, 'utf-8')
    expect(updatedConfig).toContain("outputFolder: 'test-reports/html'")

    await updateGitignore(options.output, gitignorePath)

    const gitignoreContent = await readFile(gitignorePath, 'utf-8')
    expect(gitignoreContent).toContain('test-reports/')
  })

  it('should handle "always" artifact policy', async () => {
    const options = parseSkillOptions({
      format: 'html',
      artifacts: 'always'
    })

    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    expect(artifactPolicy).toEqual({
      screenshot: 'on',
      video: 'on',
      trace: 'on'
    })

    const structure = buildDirectoryStructure(options.output)
    const reporters = generateReporterArray({ html: structure.htmlDir })

    await updatePlaywrightConfig(configPath, reporters, artifactPolicy)

    const updatedConfig = await readFile(configPath, 'utf-8')
    expect(updatedConfig).toContain("screenshot: 'on'")
    expect(updatedConfig).toContain("video: 'on'")
    expect(updatedConfig).toContain("trace: 'on'")
  })

  it('should handle "never" artifact policy', async () => {
    const options = parseSkillOptions({
      format: 'html',
      artifacts: 'never'
    })

    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    expect(artifactPolicy).toEqual({
      screenshot: 'off',
      video: 'off',
      trace: 'off'
    })

    const structure = buildDirectoryStructure(options.output)
    const reporters = generateReporterArray({ html: structure.htmlDir })

    await updatePlaywrightConfig(configPath, reporters, artifactPolicy)

    const updatedConfig = await readFile(configPath, 'utf-8')
    expect(updatedConfig).toContain("screenshot: 'off'")
    expect(updatedConfig).toContain("video: 'off'")
    expect(updatedConfig).toContain("trace: 'off'")
  })

  it('should create backup during config update', async () => {
    const options = parseSkillOptions({ format: 'html' })
    const structure = buildDirectoryStructure(options.output)
    const reporters = generateReporterArray({ html: structure.htmlDir })
    const artifactPolicy = generateArtifactRetentionPolicy(options.artifacts)

    const result = await updatePlaywrightConfig(
      configPath,
      reporters,
      artifactPolicy,
      { createBackup: true }
    )

    expect(result.backupPath).toBeDefined()
    expect(result.backupPath).toMatch(/playwright\.config\.ts\.backup\.\d+/)

    // Verify backup exists
    const backupContent = await readFile(result.backupPath!, 'utf-8')
    expect(backupContent).toContain("reporter: [['list']]") // Original config
  })
})
