/**
 * @spec T006-e2e-report-configurator
 * Integration test for custom output directory (User Story 3)
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdir, writeFile, rm, readFile, access } from 'fs/promises'
import { join } from 'path'
import { tmpdir } from 'os'
import { setupCommand } from '@/index'
import { parseSkillOptions } from '@/options-parser'
import { buildDirectoryStructure, getRequiredDirectories } from '@/directory-builder'

describe('Custom Output Directory Integration (US3)', () => {
  let testDir: string
  let configPath: string
  let gitignorePath: string

  beforeEach(async () => {
    // Create temporary test directory
    testDir = join(tmpdir(), `e2e-test-${Date.now()}`)
    await mkdir(testDir, { recursive: true })

    configPath = join(testDir, 'playwright.config.ts')
    gitignorePath = join(testDir, '.gitignore')

    // Create minimal playwright.config.ts
    const minimalConfig = `import { defineConfig } from '@playwright/test'

export default defineConfig({
  testDir: './tests',
  reporter: [['list']],
  use: {
    screenshot: 'off',
    video: 'off',
    trace: 'off'
  }
})
`
    await writeFile(configPath, minimalConfig, 'utf-8')
  })

  afterEach(async () => {
    // Cleanup test directory
    try {
      await rm(testDir, { recursive: true, force: true })
    } catch {
      // Ignore cleanup errors
    }
  })

  describe('Custom output directory', () => {
    it('should create directory structure at custom path', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'test-results' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)
      expect(result.details.directoriesCreated).toBe(5)

      // Verify directories were created
      const expectedDirs = [
        'test-results/html',
        'test-results/artifacts',
        'test-results/artifacts/screenshots',
        'test-results/artifacts/videos',
        'test-results/artifacts/traces'
      ]

      for (const dir of expectedDirs) {
        const fullPath = join(testDir, dir)
        await expect(access(fullPath)).resolves.toBeUndefined()
      }
    })

    it('should update playwright.config.ts with custom output path', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'custom/reports' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      const updatedConfig = await readFile(configPath, 'utf-8')
      expect(updatedConfig).toContain("outputFolder: 'custom/reports/html'")
    })

    it('should update .gitignore with custom output path', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'test-reports' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      const gitignoreContent = await readFile(gitignorePath, 'utf-8')
      expect(gitignoreContent).toContain('test-reports/')
      expect(gitignoreContent).toContain('# Test reports (generated by e2e-report-configurator)')
    })

    it('should handle nested custom output paths', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'my/custom/path' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      // Verify directory created
      const htmlDir = join(testDir, 'my/custom/path/html')
      await expect(access(htmlDir)).resolves.toBeUndefined()

      // Verify config
      const updatedConfig = await readFile(configPath, 'utf-8')
      expect(updatedConfig).toContain("outputFolder: 'my/custom/path/html'")

      // Verify gitignore
      const gitignoreContent = await readFile(gitignorePath, 'utf-8')
      expect(gitignoreContent).toContain('my/custom/path/')
    })
  })

  describe('Custom output with multi-format', () => {
    it('should create all format directories at custom path', async () => {
      const result = await setupCommand(
        { format: 'html,json,junit', output: 'build/reports' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)
      expect(result.details.directoriesCreated).toBe(7)

      // Verify all directories
      const expectedDirs = [
        'build/reports/html',
        'build/reports/json',
        'build/reports/junit',
        'build/reports/artifacts',
        'build/reports/artifacts/screenshots',
        'build/reports/artifacts/videos',
        'build/reports/artifacts/traces'
      ]

      for (const dir of expectedDirs) {
        const fullPath = join(testDir, dir)
        await expect(access(fullPath)).resolves.toBeUndefined()
      }
    })

    it('should update config with all custom paths', async () => {
      const result = await setupCommand(
        { format: 'html,json,junit', output: 'output' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      const updatedConfig = await readFile(configPath, 'utf-8')
      expect(updatedConfig).toContain("outputFolder: 'output/html'")
      expect(updatedConfig).toContain("outputFile: 'output/json/results.json'")
      expect(updatedConfig).toContain("outputFile: 'output/junit/results.xml'")
    })
  })

  describe('Directory structure validation', () => {
    it('should follow standardized structure at custom path', async () => {
      const options = parseSkillOptions({ output: 'my-reports' })
      const structure = buildDirectoryStructure(options.output)

      expect(structure).toEqual({
        basePath: 'my-reports',
        htmlDir: 'my-reports/html',
        jsonDir: 'my-reports/json',
        junitDir: 'my-reports/junit',
        artifactsDir: 'my-reports/artifacts',
        screenshotsDir: 'my-reports/artifacts/screenshots',
        videosDir: 'my-reports/artifacts/videos',
        tracesDir: 'my-reports/artifacts/traces'
      })
    })

    it('should filter directories by format at custom path', async () => {
      const structure = buildDirectoryStructure('custom/path')
      const requiredDirs = getRequiredDirectories(structure, 'html,json')

      expect(requiredDirs).toEqual([
        'custom/path/html',
        'custom/path/json',
        'custom/path/artifacts',
        'custom/path/artifacts/screenshots',
        'custom/path/artifacts/videos',
        'custom/path/artifacts/traces'
      ])
    })
  })

  describe('Idempotent behavior', () => {
    it('should be idempotent with custom output', async () => {
      const options = { format: 'html', output: 'test-out' }

      // First run
      const firstRun = await setupCommand(options, configPath, gitignorePath)
      expect(firstRun.success).toBe(true)
      expect(firstRun.details.directoriesCreated).toBe(5)

      // Second run
      const secondRun = await setupCommand(options, configPath, gitignorePath)
      expect(secondRun.success).toBe(true)
      expect(secondRun.details.directoriesCreated).toBe(0)
      expect(secondRun.details.directoriesExisted).toBe(5)
      expect(secondRun.details.gitignoreUpdated).toBe(false) // Already present
    })
  })

  describe('Edge cases', () => {
    it('should reject absolute paths', async () => {
      expect(() => parseSkillOptions({ output: '/absolute/path' })).toThrow(
        'Output directory must be relative'
      )
    })

    it('should reject empty output', async () => {
      expect(() => parseSkillOptions({ output: '' })).toThrow(
        'Output directory cannot be empty'
      )
    })

    it('should handle single-level custom output', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'reports' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      const updatedConfig = await readFile(configPath, 'utf-8')
      expect(updatedConfig).toContain("outputFolder: 'reports/html'")
    })

    it('should remove trailing slash from custom output', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'test-reports/' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)

      const updatedConfig = await readFile(configPath, 'utf-8')
      expect(updatedConfig).toContain("outputFolder: 'test-reports/html'")
      expect(updatedConfig).not.toContain("test-reports//html")
    })
  })

  describe('Success messages', () => {
    it('should include custom output in success message', async () => {
      const result = await setupCommand(
        { format: 'html', output: 'my-output' },
        configPath,
        gitignorePath
      )

      expect(result.success).toBe(true)
      expect(result.message).toContain('my-output')
      expect(result.message).toContain('Created 5 directories')
    })
  })
})
