/**
 * @spec P005-bom-inventory-deduction
 * Migration: Add BOM-specific constraints to store_inventory table
 *
 * Purpose: Ensure data integrity for BOM-based inventory reservation
 * Note: store_inventory already has reserved_qty field from V033
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

-- First, fix any existing data that violates the constraint
UPDATE store_inventory
SET reserved_qty = 0
WHERE reserved_qty > on_hand_qty;

-- Update available_qty to be consistent
UPDATE store_inventory
SET available_qty = on_hand_qty - reserved_qty
WHERE available_qty != (on_hand_qty - reserved_qty);

-- Add constraint to ensure on_hand_qty >= reserved_qty
-- This prevents overselling by ensuring we never reserve more than available
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_store_inventory_reserved_lte_on_hand'
    ) THEN
        ALTER TABLE store_inventory
        ADD CONSTRAINT chk_store_inventory_reserved_lte_on_hand
            CHECK (on_hand_qty >= reserved_qty);
    END IF;
END$$;

-- Add index for concurrent locking performance (if not exists)
-- Used for SELECT FOR UPDATE in reservation operations
CREATE INDEX IF NOT EXISTS idx_store_inventory_lock ON store_inventory(store_id, sku_id);

-- Add comments for BOM-related usage
COMMENT ON COLUMN store_inventory.reserved_qty IS 'Quantity locked for pending orders (预占库存). Used by P005 BOM reservation system.';
COMMENT ON COLUMN store_inventory.available_qty IS 'Computed: on_hand_qty - reserved_qty (可用库存). Auto-updated by triggers.';
COMMENT ON CONSTRAINT chk_store_inventory_reserved_lte_on_hand ON store_inventory IS 'P005: Ensures reserved quantity never exceeds on-hand quantity';
