/**
 * @spec P005-bom-inventory-deduction
 * Migration: Create bom_snapshots table
 *
 * Purpose: Store BOM formula snapshots at order creation time to lock component versions
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

-- Create bom_snapshots table
CREATE TABLE IF NOT EXISTS bom_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    sku_id UUID NOT NULL REFERENCES skus(id) ON DELETE CASCADE,
    snapshot_data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add missing columns if table structure is different (from V054)
-- V054 created with finished_sku_id/raw_material_sku_id, V059 expects sku_id/snapshot_data
DO $$
BEGIN
    -- Add sku_id as alias to finished_sku_id if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'sku_id'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'finished_sku_id'
    ) THEN
        -- V054 structure exists, skip V059 additions
        NULL;
    ELSIF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'snapshot_data'
    ) THEN
        ALTER TABLE bom_snapshots ADD COLUMN snapshot_data JSONB NOT NULL DEFAULT '{}'::jsonb;
    END IF;
END$$;

-- Create indexes for query performance (adapt to existing structure)
CREATE INDEX IF NOT EXISTS idx_snapshots_order ON bom_snapshots(order_id);
-- Index on sku_id only if column exists, otherwise use finished_sku_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'sku_id'
    ) THEN
        CREATE INDEX IF NOT EXISTS idx_snapshots_sku ON bom_snapshots(sku_id);
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'finished_sku_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'idx_snapshots_finished_sku'
    ) THEN
        CREATE INDEX idx_snapshots_finished_sku ON bom_snapshots(finished_sku_id);
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'snapshot_data'
    ) THEN
        CREATE INDEX IF NOT EXISTS idx_snapshots_data ON bom_snapshots USING GIN (snapshot_data);
    END IF;
END$$;

-- Add comments for documentation (conditional based on column existence)
COMMENT ON TABLE bom_snapshots IS 'BOM formula snapshots for order version locking (BOM配方快照)';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'snapshot_data'
    ) THEN
        EXECUTE 'COMMENT ON COLUMN bom_snapshots.snapshot_data IS ''JSONB snapshot of BOM components at reservation time''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'sku_id'
    ) THEN
        EXECUTE 'COMMENT ON COLUMN bom_snapshots.sku_id IS ''Finished product SKU (成品SKU)''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bom_snapshots' AND column_name = 'finished_sku_id'
    ) THEN
        EXECUTE 'COMMENT ON COLUMN bom_snapshots.finished_sku_id IS ''Finished product SKU (成品SKU)''';
    END IF;
END$$;

/**
 * Example snapshot_data JSON structure:
 * {
 *   "formulaId": "f001",
 *   "skuId": "sku-cocktail-001",
 *   "skuName": "威士忌可乐鸡尾酒",
 *   "components": [
 *     {
 *       "skuId": "raw001",
 *       "skuName": "威士忌",
 *       "quantity": 45,
 *       "unit": "ml",
 *       "wastageRate": 0.05
 *     },
 *     {
 *       "skuId": "raw002",
 *       "skuName": "可乐糖浆",
 *       "quantity": 150,
 *       "unit": "ml",
 *       "wastageRate": 0.02
 *     }
 *   ]
 * }
 */
