/**
 * @spec P005-bom-inventory-deduction
 * Migration: Extend inventory_transactions table for BOM deduction tracking
 *
 * Purpose: Add related_order_id and bom_snapshot_id for BOM transaction audit trail
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

-- Add new columns to inventory_transactions (if not already added by V054)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_transactions' AND column_name = 'related_order_id'
    ) THEN
        ALTER TABLE inventory_transactions
        ADD COLUMN related_order_id UUID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_transactions' AND column_name = 'bom_snapshot_id'
    ) THEN
        ALTER TABLE inventory_transactions
        ADD COLUMN bom_snapshot_id UUID;
    END IF;
END$$;

-- Create indexes for query performance
CREATE INDEX IF NOT EXISTS idx_transactions_order ON inventory_transactions(related_order_id);
CREATE INDEX IF NOT EXISTS idx_transactions_store_type ON inventory_transactions(store_id, transaction_type);

-- Add comments for documentation
COMMENT ON COLUMN inventory_transactions.related_order_id IS 'Order ID for BOM-related transactions';
COMMENT ON COLUMN inventory_transactions.bom_snapshot_id IS 'BOM snapshot ID for audit trail (shows which formula version was used)';

/**
 * Note: transaction_type enum values will be extended at application level
 * New types supported:
 * - BOM_RESERVATION: Inventory reserved for order (informational)
 * - BOM_DEDUCTION: Actual inventory consumption on fulfillment
 * - RESERVATION_RELEASE: Reservation released (cancellation/expiry)
 */
