/**
 * @spec O012-order-inventory-reservation
 * Order Cancellation Service
 *
 * Purpose: Handles order cancellation and inventory reservation release
 * Integrates with P005 InventoryReservationService for inventory management
 *
 * Author: Generated by O012 spec
 * Date: 2026-01-14
 */

package com.cinema.order.service;

import com.cinema.inventory.service.InventoryReservationService;
import com.cinema.order.domain.OrderStatus;
import com.cinema.order.domain.ProductOrder;
import com.cinema.order.exception.OrderNotFoundException;
import com.cinema.order.repository.JdbcProductOrderRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Order Cancellation Service
 *
 * Handles order cancellation workflow:
 * 1. Validate order exists and is cancellable
 * 2. Release inventory reservations (via P005 service)
 * 3. Update order status to CANCELLED
 *
 * Integration with P005:
 * - Uses InventoryReservationService.releaseReservation() to free reserved inventory
 * - Reservation release failure does not block order cancellation (logged as warning)
 *
 * @see InventoryReservationService
 */
@Service
public class OrderCancellationService {

    private static final Logger logger = LoggerFactory.getLogger(OrderCancellationService.class);

    private final InventoryReservationService reservationService;
    private final JdbcProductOrderRepository orderRepository;

    public OrderCancellationService(
            InventoryReservationService reservationService,
            JdbcProductOrderRepository orderRepository
    ) {
        this.reservationService = reservationService;
        this.orderRepository = orderRepository;
    }

    /**
     * Cancel order and release inventory reservations
     *
     * @param orderId Order ID
     * @param cancelReason Cancellation reason
     * @throws OrderNotFoundException if order not found
     * @throws IllegalStateException if order is not cancellable
     */
    @Transactional
    public void cancelOrder(UUID orderId, String cancelReason) {
        logger.info("Starting order cancellation: orderId={}, reason={}", orderId, cancelReason);

        // Step 1: Validate order exists
        ProductOrder order = orderRepository.findById(orderId);
        if (order == null) {
            logger.error("Order not found: {}", orderId);
            throw new OrderNotFoundException(orderId.toString());
        }

        // Step 2: Validate order is cancellable
        if (!isCancellable(order)) {
            logger.error("Order is not cancellable: orderId={}, status={}", orderId, order.getStatus());
            throw new IllegalStateException(
                    "Order is not cancellable. Current status: " + order.getStatus()
            );
        }

        // Step 3: Release inventory reservations (P005 integration)
        try {
            int releasedCount = reservationService.releaseReservation(orderId);
            logger.info("Successfully released {} inventory reservations for order: {}", 
                    releasedCount, orderId);
        } catch (Exception e) {
            // Log error but do not block cancellation
            // Reservation might have been already released by cleanup job
            logger.warn("Failed to release inventory reservations for order {}: {}. " +
                    "Proceeding with order cancellation.", orderId, e.getMessage());
        }

        // Step 4: Update order status to CANCELLED
        order.setStatus(OrderStatus.CANCELLED);
        order.setCancelledTime(LocalDateTime.now());
        order.setCancelReason(cancelReason != null ? cancelReason : "Order cancelled by user");

        int updatedRows = orderRepository.updateOrderStatus(order);
        if (updatedRows == 0) {
            logger.error("Failed to update order status to CANCELLED: {}", orderId);
            throw new IllegalStateException("Failed to cancel order: " + orderId);
        }

        logger.info("Order cancellation completed: orderId={}", orderId);
    }

    /**
     * Check if order can be cancelled
     *
     * Cancellable statuses:
     * - PENDING_PAYMENT (not yet paid)
     * - PAID (paid but not shipped)
     *
     * Non-cancellable statuses:
     * - SHIPPED (already shipped to customer)
     * - COMPLETED (order fulfilled)
     * - CANCELLED (already cancelled)
     *
     * @param order Order to check
     * @return true if order can be cancelled
     */
    private boolean isCancellable(ProductOrder order) {
        OrderStatus status = order.getStatus();
        return status == OrderStatus.PENDING_PAYMENT || status == OrderStatus.PAID;
    }
}
