openapi: 3.0.3
info:
  title: 采购入库模块 API
  description: |
    N001-purchase-inbound 采购入库模块 API 规范

    功能包括：
    - 采购订单管理 (CRUD, 审批)
    - 收货入库管理 (创建, 确认, 库存更新)
    - 供应商查询
  version: 1.0.0
  contact:
    name: N001-purchase-inbound

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: PurchaseOrders
    description: 采购订单管理
  - name: GoodsReceipts
    description: 收货入库管理
  - name: Suppliers
    description: 供应商查询

paths:
  # ==================== 采购订单 ====================
  /purchase-orders:
    get:
      tags:
        - PurchaseOrders
      summary: 获取采购订单列表
      operationId: listPurchaseOrders
      parameters:
        - name: storeId
          in: query
          description: 门店ID筛选
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          description: 状态筛选
          schema:
            $ref: '#/components/schemas/PurchaseOrderStatus'
        - name: page
          in: query
          description: 页码 (从1开始)
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 每页数量
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderListResponse'

    post:
      tags:
        - PurchaseOrders
      summary: 创建采购订单
      operationId: createPurchaseOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePurchaseOrderRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /purchase-orders/{id}:
    get:
      tags:
        - PurchaseOrders
      summary: 获取采购订单详情
      operationId: getPurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderDetailResponse'
        '404':
          description: 订单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - PurchaseOrders
      summary: 更新采购订单
      operationId: updatePurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePurchaseOrderRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderResponse'
        '400':
          description: 请求参数错误
        '404':
          description: 订单不存在
        '409':
          description: 版本冲突

    delete:
      tags:
        - PurchaseOrders
      summary: 删除采购订单
      description: 仅允许删除草稿状态的订单
      operationId: deletePurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 删除成功
        '400':
          description: 订单状态不允许删除
        '404':
          description: 订单不存在

  /purchase-orders/{id}/submit:
    post:
      tags:
        - PurchaseOrders
      summary: 提交审核
      description: 将草稿订单提交审核
      operationId: submitPurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 提交成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderResponse'
        '400':
          description: 订单状态不允许提交

  /purchase-orders/{id}/approve:
    post:
      tags:
        - PurchaseOrders
      summary: 审批通过
      operationId: approvePurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 审批成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderResponse'
        '400':
          description: 订单状态不允许审批

  /purchase-orders/{id}/reject:
    post:
      tags:
        - PurchaseOrders
      summary: 审批拒绝
      operationId: rejectPurchaseOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reason
              properties:
                reason:
                  type: string
                  description: 拒绝原因
                  maxLength: 500
      responses:
        '200':
          description: 拒绝成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrderResponse'
        '400':
          description: 订单状态不允许拒绝

  # ==================== 收货入库 ====================
  /goods-receipts:
    get:
      tags:
        - GoodsReceipts
      summary: 获取收货入库单列表
      operationId: listGoodsReceipts
      parameters:
        - name: storeId
          in: query
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/GoodsReceiptStatus'
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsReceiptListResponse'

    post:
      tags:
        - GoodsReceipts
      summary: 创建收货入库单
      description: 基于已审核的采购订单创建收货入库单
      operationId: createGoodsReceipt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGoodsReceiptRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsReceiptResponse'
        '400':
          description: 请求参数错误

  /goods-receipts/{id}:
    get:
      tags:
        - GoodsReceipts
      summary: 获取收货入库单详情
      operationId: getGoodsReceipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsReceiptDetailResponse'
        '404':
          description: 收货单不存在

  /goods-receipts/{id}/confirm:
    post:
      tags:
        - GoodsReceipts
      summary: 确认收货
      description: 确认收货并更新库存
      operationId: confirmGoodsReceipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 确认成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsReceiptResponse'
        '400':
          description: 收货单状态不允许确认

  # ==================== 供应商 ====================
  /suppliers:
    get:
      tags:
        - Suppliers
      summary: 获取供应商列表
      operationId: listSuppliers
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, INACTIVE]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierListResponse'

components:
  schemas:
    # ==================== 通用 ====================
    ApiResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        timestamp:
          type: string
          format: date-time
        message:
          type: string

    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            success:
              type: boolean
              example: false
            error:
              type: string
              description: 错误编号
              example: PO_NTF_001
            details:
              type: object

    # ==================== 枚举 ====================
    PurchaseOrderStatus:
      type: string
      enum:
        - DRAFT
        - PENDING_APPROVAL
        - APPROVED
        - REJECTED
        - PARTIAL_RECEIVED
        - FULLY_RECEIVED
        - CLOSED
      description: |
        - DRAFT: 草稿
        - PENDING_APPROVAL: 待审核
        - APPROVED: 已审核
        - REJECTED: 已拒绝
        - PARTIAL_RECEIVED: 部分收货
        - FULLY_RECEIVED: 全部收货
        - CLOSED: 已关闭

    GoodsReceiptStatus:
      type: string
      enum:
        - PENDING
        - CONFIRMED
        - CANCELLED
      description: |
        - PENDING: 待收货
        - CONFIRMED: 已确认
        - CANCELLED: 已取消

    QualityStatus:
      type: string
      enum:
        - QUALIFIED
        - UNQUALIFIED
        - PENDING_CHECK
      description: |
        - QUALIFIED: 合格
        - UNQUALIFIED: 不合格
        - PENDING_CHECK: 待检验

    # ==================== 供应商 ====================
    Supplier:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        contactName:
          type: string
        contactPhone:
          type: string
        status:
          type: string

    SupplierListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Supplier'

    # ==================== 采购订单 ====================
    CreatePurchaseOrderRequest:
      type: object
      required:
        - supplierId
        - storeId
        - items
      properties:
        supplierId:
          type: string
          format: uuid
        storeId:
          type: string
          format: uuid
        plannedArrivalDate:
          type: string
          format: date
        remarks:
          type: string
          maxLength: 500
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/PurchaseOrderItemRequest'

    PurchaseOrderItemRequest:
      type: object
      required:
        - skuId
        - quantity
        - unitPrice
      properties:
        skuId:
          type: string
          format: uuid
        quantity:
          type: number
          minimum: 0.001
        unitPrice:
          type: number
          minimum: 0

    UpdatePurchaseOrderRequest:
      type: object
      properties:
        supplierId:
          type: string
          format: uuid
        plannedArrivalDate:
          type: string
          format: date
        remarks:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseOrderItemRequest'
        version:
          type: integer
          description: 乐观锁版本号

    PurchaseOrder:
      type: object
      properties:
        id:
          type: string
          format: uuid
        orderNumber:
          type: string
        supplier:
          $ref: '#/components/schemas/Supplier'
        store:
          $ref: '#/components/schemas/Store'
        status:
          $ref: '#/components/schemas/PurchaseOrderStatus'
        totalAmount:
          type: number
        plannedArrivalDate:
          type: string
          format: date
        remarks:
          type: string
        createdAt:
          type: string
          format: date-time
        version:
          type: integer

    PurchaseOrderItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        sku:
          $ref: '#/components/schemas/Sku'
        quantity:
          type: number
        unitPrice:
          type: number
        lineAmount:
          type: number
        receivedQty:
          type: number
        pendingQty:
          type: number

    PurchaseOrderResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PurchaseOrder'

    PurchaseOrderDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: '#/components/schemas/PurchaseOrder'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/PurchaseOrderItem'

    PurchaseOrderListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/PurchaseOrder'
            total:
              type: integer
            page:
              type: integer
            pageSize:
              type: integer

    # ==================== 收货入库 ====================
    CreateGoodsReceiptRequest:
      type: object
      required:
        - purchaseOrderId
        - items
      properties:
        purchaseOrderId:
          type: string
          format: uuid
        remarks:
          type: string
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/GoodsReceiptItemRequest'

    GoodsReceiptItemRequest:
      type: object
      required:
        - skuId
        - receivedQty
      properties:
        skuId:
          type: string
          format: uuid
        receivedQty:
          type: number
          minimum: 0
        qualityStatus:
          $ref: '#/components/schemas/QualityStatus'
        rejectionReason:
          type: string

    GoodsReceipt:
      type: object
      properties:
        id:
          type: string
          format: uuid
        receiptNumber:
          type: string
        purchaseOrder:
          $ref: '#/components/schemas/PurchaseOrder'
        store:
          $ref: '#/components/schemas/Store'
        status:
          $ref: '#/components/schemas/GoodsReceiptStatus'
        receivedByName:
          type: string
        receivedAt:
          type: string
          format: date-time
        remarks:
          type: string
        createdAt:
          type: string
          format: date-time

    GoodsReceiptItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        sku:
          $ref: '#/components/schemas/Sku'
        orderedQty:
          type: number
        receivedQty:
          type: number
        qualityStatus:
          $ref: '#/components/schemas/QualityStatus'
        rejectionReason:
          type: string

    GoodsReceiptResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/GoodsReceipt'

    GoodsReceiptDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: '#/components/schemas/GoodsReceipt'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/GoodsReceiptItem'

    GoodsReceiptListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/GoodsReceipt'
            total:
              type: integer
            page:
              type: integer
            pageSize:
              type: integer

    # ==================== 引用实体 ====================
    Store:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string

    Sku:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        mainUnit:
          type: string
