/**
 * @spec P005-bom-inventory-deduction
 * Error Handler Utility
 *
 * Purpose: Centralized error handling for inventory API errors
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

import Taro from '@tarojs/taro';

/**
 * API Error interface
 */
export interface ApiError {
  success: false;
  error: string;
  message: string;
  details?: Record<string, any>;
  timestamp: string;
}

/**
 * Inventory shortage detail
 */
export interface InventoryShortage {
  skuId: string;
  skuName: string;
  available: number;
  required: number;
  shortage: number;
  unit: string;
}

/**
 * Handle inventory API errors
 * Displays appropriate UI feedback based on error code
 *
 * @param error API error object
 */
export function handleInventoryError(error: ApiError): void {
  const errorHandlers: Record<string, (err: ApiError) => void> = {
    /**
     * INV_BIZ_001: Insufficient inventory
     * Display detailed shortage information
     */
    'INV_BIZ_001': (err) => {
      const shortages: InventoryShortage[] = err.details?.shortages || [];
      const shortageList = shortages
        .map((s) => `${s.skuName}: 需要${s.required}${s.unit}, 可用${s.available}${s.unit}`)
        .join('\n');

      Taro.showModal({
        title: '库存不足',
        content: shortageList || '所选商品库存不足，请减少数量或联系店员',
        showCancel: false,
        confirmText: '知道了'
      });
    },

    /**
     * INV_NTF_001: No active reservations
     */
    'INV_NTF_001': () => {
      Taro.showToast({
        title: '该订单没有活跃的库存预占记录',
        icon: 'none',
        duration: 2000
      });
    },

    /**
     * INV_NTF_003: BOM formula not found
     */
    'INV_NTF_003': () => {
      Taro.showModal({
        title: '配方未配置',
        content: 'BOM配方未配置，请联系管理员',
        showCancel: false
      });
    },

    /**
     * INV_BIZ_002: Insufficient current inventory for deduction
     * Data inconsistency - alert admin
     */
    'INV_BIZ_002': (err) => {
      const skuName = err.details?.skuName || '商品';
      Taro.showModal({
        title: '库存数据异常',
        content: `${skuName}的现存库存低于预占库存，请联系管理员核查`,
        showCancel: false
      });
      // TODO: Trigger admin notification
    },

    /**
     * INV_BIZ_003: Reservation expired
     */
    'INV_BIZ_003': () => {
      Taro.showModal({
        title: '预占超时',
        content: '库存预占已超时，请重新下单',
        showCancel: false,
        success: () => {
          // Navigate back to order page
          Taro.navigateBack();
        }
      });
    },

    /**
     * INV_DUP_002: Order already fulfilled
     */
    'INV_DUP_002': () => {
      Taro.showToast({
        title: '订单已履约，无法重复操作',
        icon: 'none',
        duration: 2000
      });
    },

    /**
     * INV_SYS_001: Internal server error
     */
    'INV_SYS_001': () => {
      Taro.showToast({
        title: '系统异常，请稍后重试',
        icon: 'error',
        duration: 2000
      });
    },

    /**
     * INV_SYS_004: Lock timeout
     */
    'INV_SYS_004': () => {
      Taro.showToast({
        title: '系统繁忙，请稍后重试',
        icon: 'none',
        duration: 2000
      });
    }
  };

  const handler = errorHandlers[error.error];

  if (handler) {
    handler(error);
  } else {
    // Fallback for unknown errors
    Taro.showToast({
      title: error.message || '操作失败',
      icon: 'none',
      duration: 2000
    });
  }
}

/**
 * Format error message for display
 *
 * @param error API error object
 * @returns Formatted error message
 */
export function formatErrorMessage(error: ApiError): string {
  const errorMessages: Record<string, string> = {
    'INV_BIZ_001': '库存不足',
    'INV_NTF_001': '没有活跃的预占记录',
    'INV_NTF_003': 'BOM配方未配置',
    'INV_BIZ_002': '库存数据异常',
    'INV_BIZ_003': '预占已超时',
    'INV_DUP_002': '订单已履约',
    'INV_SYS_001': '系统异常',
    'INV_SYS_004': '系统繁忙'
  };

  return errorMessages[error.error] || error.message || '未知错误';
}
