/**
 * @spec P005-bom-inventory-deduction
 * BomSnapshot Repository
 *
 * Purpose: Data access layer for BOM formula snapshots
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.repository;

import com.cinema.inventory.entity.BomSnapshot;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

/**
 * BOM Snapshot Repository
 *
 * Provides data access methods for BOM formula snapshots.
 * Snapshots preserve the exact BOM composition at order creation time.
 *
 * @see com.cinema.inventory.service.BomSnapshotService
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Repository
public interface BomSnapshotRepository extends JpaRepository<BomSnapshot, UUID> {

    /**
     * Find all BOM snapshots for an order
     * Each snapshot represents one finished product in the order
     *
     * @param orderId Order ID
     * @return List of BOM snapshots
     */
    List<BomSnapshot> findByOrderId(UUID orderId);

    /**
     * Find BOM snapshots for a specific SKU in an order
     * Useful for querying the formula used for a specific product
     *
     * @param orderId Order ID
     * @param skuId Finished product SKU ID
     * @return List of BOM snapshots (typically one per order item)
     */
    List<BomSnapshot> findByOrderIdAndSkuId(UUID orderId, UUID skuId);
}
