/**
 * @spec P005-bom-inventory-deduction
 * InventoryTransaction JPA Repository
 *
 * Purpose: JPA-based data access for inventory transactions (P005 specific)
 * Note: Works alongside InventoryTransactionRepository (Supabase REST) from P004
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.repository;

import com.cinema.inventory.entity.InventoryTransaction;
import com.cinema.inventory.entity.InventoryTransaction.TransactionType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Inventory Transaction JPA Repository
 *
 * JPA-based repository for BOM-related inventory transactions.
 * Provides type-safe queries with full JPA support.
 *
 * @see com.cinema.inventory.entity.InventoryTransaction
 * @see com.cinema.inventory.service.InventoryTransactionService
 */
@Repository
public interface InventoryTransactionJpaRepository extends
        JpaRepository<InventoryTransaction, UUID>,
        JpaSpecificationExecutor<InventoryTransaction> {

    /**
     * Find transactions by order ID
     * Used to query all inventory changes related to a specific order
     *
     * @param orderId Order ID
     * @return List of transactions
     */
    List<InventoryTransaction> findByRelatedOrderId(UUID orderId);

    /**
     * Find transactions by order ID and type
     *
     * @param orderId Order ID
     * @param transactionType Transaction type
     * @return List of transactions
     */
    List<InventoryTransaction> findByRelatedOrderIdAndTransactionType(
            UUID orderId,
            TransactionType transactionType
    );

    /**
     * Find transactions by BOM snapshot ID
     * Used for audit trail of which formula was used
     *
     * @param bomSnapshotId BOM snapshot ID
     * @return List of transactions
     */
    List<InventoryTransaction> findByBomSnapshotId(UUID bomSnapshotId);

    /**
     * Find transactions by store, SKU, and date range
     * Used for inventory transaction log queries
     *
     * @param storeId Store ID
     * @param skuId SKU ID
     * @param startDate Start date (inclusive)
     * @param endDate End date (inclusive)
     * @param pageable Pagination and sorting
     * @return Page of transactions
     */
    Page<InventoryTransaction> findByStoreIdAndSkuIdAndOperatedAtBetween(
            UUID storeId,
            UUID skuId,
            Instant startDate,
            Instant endDate,
            Pageable pageable
    );

    /**
     * Find transactions by transaction type
     * Used for filtering by BOM_DEDUCTION, etc.
     *
     * @param transactionType Transaction type
     * @param pageable Pagination and sorting
     * @return Page of transactions
     */
    Page<InventoryTransaction> findByTransactionType(
            TransactionType transactionType,
            Pageable pageable
    );
}
