/**
 * @spec P005-bom-inventory-deduction
 * InventoryReservation Repository
 *
 * Purpose: Data access layer for inventory reservations
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.repository;

import com.cinema.inventory.entity.InventoryReservation;
import com.cinema.inventory.entity.InventoryReservation.ReservationStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Inventory Reservation Repository
 *
 * Provides data access methods for inventory reservation operations.
 *
 * @see com.cinema.inventory.service.InventoryReservationService
 */
@Repository
public interface InventoryReservationRepository extends JpaRepository<InventoryReservation, UUID> {

    /**
     * Find all reservations for an order
     *
     * @param orderId Order ID
     * @return List of reservations
     */
    List<InventoryReservation> findByOrderId(UUID orderId);

    /**
     * Find active reservations for an order
     *
     * @param orderId Order ID
     * @param status Reservation status (typically ACTIVE)
     * @return List of active reservations
     */
    List<InventoryReservation> findByOrderIdAndStatus(UUID orderId, ReservationStatus status);

    /**
     * Find expired reservations that need cleanup
     * Used by scheduled job to release expired reservations
     *
     * @param status Reservation status (ACTIVE)
     * @param expiryTime Current time to compare against expires_at
     * @return List of expired reservations
     */
    @Query("SELECT r FROM InventoryReservation r " +
           "WHERE r.status = :status " +
           "AND r.expiresAt IS NOT NULL " +
           "AND r.expiresAt <= :expiryTime")
    List<InventoryReservation> findExpiredReservations(
        @Param("status") ReservationStatus status,
        @Param("expiryTime") Instant expiryTime
    );

    /**
     * Update reservation status by order ID
     * Used for bulk status updates (e.g., fulfill all reservations for an order)
     *
     * @param orderId Order ID
     * @param newStatus New status to set
     * @return Number of rows updated
     */
    @Modifying
    @Query("UPDATE InventoryReservation r " +
           "SET r.status = :newStatus, " +
           "r.fulfilledAt = CURRENT_TIMESTAMP " +
           "WHERE r.orderId = :orderId " +
           "AND r.status = 'ACTIVE'")
    int updateStatusByOrderId(
        @Param("orderId") UUID orderId,
        @Param("newStatus") ReservationStatus newStatus
    );

    /**
     * Check if order has active reservations
     *
     * @param orderId Order ID
     * @return true if active reservations exist
     */
    boolean existsByOrderIdAndStatus(UUID orderId, ReservationStatus status);
}
