/**
 * @spec P005-bom-inventory-deduction
 * Inventory Repository
 *
 * Purpose: Data access layer for inventory with row-level locking support
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.repository;

import com.cinema.inventory.entity.Inventory;
import jakarta.persistence.LockModeType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Inventory Repository
 *
 * Provides data access methods for inventory operations.
 * Includes pessimistic locking support for concurrent reservation handling.
 *
 * Key methods:
 * - findByStoreIdAndSkuIdForUpdate: Acquires row-level lock (SELECT FOR UPDATE)
 *   Used in reservation and deduction operations to prevent race conditions
 *
 * @see com.cinema.inventory.service.InventoryReservationService
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Repository
public interface InventoryRepository extends JpaRepository<Inventory, UUID> {

    /**
     * Find inventory by store and SKU without locking
     * Use for read-only queries
     *
     * @param storeId Store ID
     * @param skuId SKU ID
     * @return Optional inventory record
     */
    Optional<Inventory> findByStoreIdAndSkuId(UUID storeId, UUID skuId);

    /**
     * Find inventory by SKU and store without locking
     * Use for read-only queries (alternative parameter order)
     *
     * @param skuId SKU ID
     * @param storeId Store ID
     * @return Optional inventory record
     */
    Optional<Inventory> findBySkuIdAndStoreId(UUID skuId, UUID storeId);

    /**
     * Find inventory by store and SKU with pessimistic lock (SELECT FOR UPDATE)
     * Acquires row-level lock until transaction commits/rollbacks
     *
     * CRITICAL: Must be called within @Transactional context
     * Prevents concurrent modifications during reservation/deduction
     *
     * Lock timeout: 10 seconds (configured in TransactionConfig)
     * If lock cannot be acquired within timeout, throws exception
     *
     * Example usage:
     * <pre>
     * {@code
     * @Transactional
     * public void reserveInventory(UUID storeId, UUID skuId, BigDecimal quantity) {
     *     Inventory inventory = inventoryRepository
     *         .findByStoreIdAndSkuIdForUpdate(storeId, skuId)
     *         .orElseThrow(() -> new InventoryNotFoundException());
     *
     *     // Now we have exclusive lock on this row
     *     BigDecimal available = inventory.calculateAvailableForReservation();
     *     if (available.compareTo(quantity) < 0) {
     *         throw new InsufficientInventoryException();
     *     }
     *
     *     inventory.setReservedQty(inventory.getReservedQty().add(quantity));
     *     inventoryRepository.save(inventory);
     *     // Lock released when transaction commits
     * }
     * }
     * </pre>
     *
     * @param storeId Store ID
     * @param skuId SKU ID
     * @return Optional inventory record with pessimistic lock acquired
     */
    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("SELECT i FROM Inventory i WHERE i.storeId = :storeId AND i.skuId = :skuId")
    Optional<Inventory> findByStoreIdAndSkuIdForUpdate(
        @Param("storeId") UUID storeId,
        @Param("skuId") UUID skuId
    );
}
