# E2E Scenario: 跨门店库存调拨
# Generated for e2e-admin testing
# Date: 2025-12-30

scenario_id: E2E-INVENTORY-005
spec_ref: P005
title: 跨门店库存调拨
description: 验证从仓库充足的门店调拨库存到缺货门店

tags:
  module:
    - inventory
  channel:
    - web
  deploy:
    - saas
    - private
  priority: p2
  smoke: false

preconditions:
  role: warehouse_manager

steps:
  - action: login
    system: b-end
    params:
      testdata_ref: inventoryTestData.warehouse_manager
    description: 仓库经理登录系统

  - action: navigate
    system: b-end
    params:
      path: /inventory/transfer
    description: 导航到库存调拨页面

  - action: create_transfer_order
    system: b-end
    params:
      from_store: inventoryTestData.store_a
      to_store: inventoryTestData.store_b
      sku: inventoryTestData.product_sku
      quantity: 50
    description: 创建调拨单（门店A → 门店B，50 件）

  - action: confirm_transfer
    system: b-end
    params:
      testdata_ref: inventoryTestData.transfer_order
    description: 确认调拨

  - action: wait
    params:
      duration: 2000
    description: 等待系统处理

assertions:
  - type: ui
    check: element_visible
    params:
      selector: .transfer-success
      text: "调拨成功"
    timeout: 5000

  - type: api
    check: inventory_updated
    params:
      store: inventoryTestData.store_a
      sku: inventoryTestData.product_sku
      expected_change: -50
    timeout: 3000

  - type: api
    check: inventory_updated
    params:
      store: inventoryTestData.store_b
      sku: inventoryTestData.product_sku
      expected_change: +50
    timeout: 3000

artifacts:
  trace: always
  video: on-failure
  screenshot: on-failure

metadata:
  created_at: "2025-12-30T10:30:00Z"
  created_by: e2e-admin-skill
  version: "1.0.0"
