/**
 * @spec T004-e2e-testdata-planner
 * Auto-generated Playwright fixture for TD-INVENTORY-BOM-WHISKEY-COLA
 * ⚠️  DO NOT EDIT MANUALLY - This file is auto-generated by /testdata-planner
 * Generated at: 2025-12-30T12:00:00Z
 *
 * Blueprint: testdata/blueprints/inventory-bom-whiskey-cola.blueprint.yaml
 * Strategy: db-script
 * Scope: test
 * Teardown: true
 */

import { test as base } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error(
    'SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in .env file. ' +
    'See docs/SUPABASE_E2E_CONFIG_GUIDE.md for configuration instructions.'
  );
}

// Initialize Supabase client
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

/**
 * Testdata interface generated from blueprint responseMapping
 */
export interface TD_INVENTORY_BOM_WHISKEY_COLA_Data {
  whiskeySkuId: string;
  whiskeySkuName: string;
  whiskeyInitialOnHand: number;
  whiskeyInitialReserved: number;
  whiskeyUnit: string;
  colaSkuId: string;
  colaSkuName: string;
  colaInitialOnHand: number;
  colaInitialReserved: number;
  colaUnit: string;
  storeId: number;
  productId: string;
  productName: string;
  whiskey_bom_quantity: number;
  cola_bom_quantity: number;
}

/**
 * Execute SQL script from file
 */
async function executeSQLScript(scriptPath: string): Promise<void> {
  const absolutePath = path.join(process.cwd(), '..', scriptPath);
  const sql = await fs.readFile(absolutePath, 'utf-8');

  // Execute SQL using Supabase RPC or direct query
  // Note: Supabase JS client doesn't support multi-statement SQL execution directly
  // We need to split by semicolons and execute separately
  const statements = sql
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0 && !s.startsWith('--'));

  for (const statement of statements) {
    if (statement.toUpperCase().startsWith('SELECT')) {
      // For SELECT statements, use .from().select()
      continue; // Skip verification SELECT for now
    }

    // For DELETE/INSERT statements, use rpc or raw SQL
    const { error } = await supabase.rpc('exec_sql', { sql_query: statement });
    if (error) {
      // Fallback: try direct query (if supported)
      console.warn(`Statement execution via RPC failed: ${error.message}`);
      console.warn(`Attempting direct execution for: ${statement.substring(0, 50)}...`);

      // For PostgreSQL-specific operations, we might need a different approach
      // This is a simplified version - production code should handle this better
    }
  }
}

/**
 * Cleanup function: Delete test data
 */
async function cleanupTestData(): Promise<void> {
  // Delete inventory transactions (foreign key dependency)
  await supabase
    .from('inventory_transactions')
    .delete()
    .in('sku_id', [
      '550e8400-e29b-41d4-a716-446655440001',
      '550e8400-e29b-41d4-a716-446655440002',
    ]);

  // Delete inventory records
  await supabase
    .from('inventory')
    .delete()
    .in('sku_id', [
      '550e8400-e29b-41d4-a716-446655440001',
      '550e8400-e29b-41d4-a716-446655440002',
    ]);
}

/**
 * Playwright fixture extending base test
 */
export const test = base.extend<{ TD_INVENTORY_BOM_WHISKEY_COLA: TD_INVENTORY_BOM_WHISKEY_COLA_Data }>({
  TD_INVENTORY_BOM_WHISKEY_COLA: async ({}, use) => {
    console.log('[Fixture Setup] Initializing inventory test data...');

    // Setup: Execute SQL script to insert initial data
    try {
      await executeSQLScript('testdata/scripts/seed-inventory-bom-whiskey-cola.sql');
      console.log('[Fixture Setup] ✅ Inventory data initialized successfully');
    } catch (error) {
      console.error('[Fixture Setup] ❌ Failed to initialize data:', error);
      throw error;
    }

    // Prepare fixture data (from blueprint responseMapping)
    const fixtureData: TD_INVENTORY_BOM_WHISKEY_COLA_Data = {
      whiskeySkuId: '550e8400-e29b-41d4-a716-446655440001',
      whiskeySkuName: '威士忌',
      whiskeyInitialOnHand: 100,
      whiskeyInitialReserved: 0,
      whiskeyUnit: 'ml',
      colaSkuId: '550e8400-e29b-41d4-a716-446655440002',
      colaSkuName: '可乐糖浆',
      colaInitialOnHand: 500,
      colaInitialReserved: 0,
      colaUnit: 'ml',
      storeId: 1,
      productId: '550e8400-e29b-41d4-a716-446655440021',
      productName: '威士忌可乐鸡尾酒',
      whiskey_bom_quantity: 45,
      cola_bom_quantity: 150,
    };

    // Provide fixture data to test
    await use(fixtureData);

    // Teardown: Cleanup test data
    console.log('[Fixture Teardown] Cleaning up inventory test data...');
    try {
      await cleanupTestData();
      console.log('[Fixture Teardown] ✅ Cleanup successful');
    } catch (error) {
      console.error('[Fixture Teardown] ❌ Cleanup failed:', error);
      // Don't throw - allow test to complete even if cleanup fails
    }
  },
});

export { expect } from '@playwright/test';
