/**
 * @spec O004-beverage-sku-reuse
 * Auto-generated fixture for TD-BOM-COCKTAIL-001
 * ⚠️  DO NOT EDIT MANUALLY - This file is auto-generated
 * Generated at: 2025-12-31T12:00:00Z
 * Generated by: e2e-testdata-planner
 */
import { test as base } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * SKU Interface
 */
interface SKU {
  code: string;
  name: string;
  type: string;
  category: string;
  price: string;
  unit: string;
}

/**
 * Test Data Interface for TD-BOM-COCKTAIL-001
 * BOM配方SKU选择器过滤测试数据
 */
export interface TD_BOM_COCKTAIL_001_Data {
  expectedSkuCount: number;
  finishedProductSkus: SKU[];
  packagingSkus: SKU[];
  rawMaterialSkus: SKU[];
  adminCredentials: {
    username: string;
    password: string;
  };
}

/**
 * Playwright Test with TD-BOM-COCKTAIL-001 Fixture
 *
 * Usage:
 * ```typescript
 * import { test } from './fixtures/testdata/testdata-TD-BOM-COCKTAIL-001.fixture';
 *
 * test('SKU选择器过滤', async ({ page, TD_BOM_COCKTAIL_001 }) => {
 *   // expectedSkuCount: 应显示3个finished_product SKU
 *   await expect(skuOptions).toHaveCount(TD_BOM_COCKTAIL_001.expectedSkuCount);
 *
 *   // finishedProductSkus: 应显示的SKU列表
 *   TD_BOM_COCKTAIL_001.finishedProductSkus.forEach(sku => {
 *     await expect(page.locator(`text="${sku.name}"`)).toBeVisible();
 *   });
 *
 *   // packagingSkus: 不应显示的SKU列表
 *   TD_BOM_COCKTAIL_001.packagingSkus.forEach(sku => {
 *     await expect(page.locator(`text="${sku.name}"`)).not.toBeVisible();
 *   });
 * });
 * ```
 */
export const test = base.extend<{ TD_BOM_COCKTAIL_001: TD_BOM_COCKTAIL_001_Data }>({
  TD_BOM_COCKTAIL_001: [async ({}, use) => {
    // ========== Setup: Load seed data ==========
    const seedPath = path.join(process.cwd(), 'testdata/seeds/bom-filter-skus.json');

    // Read and parse seed file
    const seedContent = fs.readFileSync(seedPath, 'utf-8');
    const seedData = JSON.parse(seedContent);

    // Find the specific seed item by key
    const bomFilterData = seedData.find((item: any) => item.key === 'bom-filter-test');

    if (!bomFilterData) {
      throw new Error('Seed key "bom-filter-test" not found in testdata/seeds/bom-filter-skus.json');
    }

    // Map seed data to fixture interface
    const fixtureData: TD_BOM_COCKTAIL_001_Data = {
      expectedSkuCount: bomFilterData.expected_sku_count,
      finishedProductSkus: bomFilterData.finished_product_skus.map((sku: any) => ({
        code: sku.code,
        name: sku.name,
        type: sku.type,
        category: sku.category,
        price: sku.price,
        unit: sku.unit
      })),
      packagingSkus: bomFilterData.packaging_skus.map((sku: any) => ({
        code: sku.code,
        name: sku.name,
        type: sku.type,
        category: sku.category,
        price: sku.price,
        unit: sku.unit
      })),
      rawMaterialSkus: bomFilterData.raw_material_skus.map((sku: any) => ({
        code: sku.code,
        name: sku.name,
        type: sku.type,
        category: sku.category,
        price: sku.price,
        unit: sku.unit
      })),
      adminCredentials: {
        username: bomFilterData.admin_credentials.username,
        password: bomFilterData.admin_credentials.password
      }
    };

    // Provide fixture data to test
    await use(fixtureData);

    // ========== Teardown ==========
    // No teardown needed for seed strategy
    // Seed data is static and doesn't require cleanup

  }, { scope: 'test' }]  // 每个测试独立加载数据
});

export { expect } from '@playwright/test';
