/**
 * @spec O004-beverage-sku-reuse
 * Auto-generated fixture for TD-SKU-BEVERAGE-001
 * ⚠️  DO NOT EDIT MANUALLY - This file is auto-generated
 * Generated at: 2025-12-31T12:00:00Z
 * Generated by: e2e-testdata-planner
 */
import { test as base } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Test Data Interface for TD-SKU-BEVERAGE-001
 * 饮品成品SKU测试数据（薄荷威士忌鸡尾酒）
 */
export interface TD_SKU_BEVERAGE_001_Data {
  skuCode: string;
  skuName: string;
  skuType: string;
  categoryPath: string;
  price: string;
  unit: string;
  status: string;
  adminCredentials: {
    username: string;
    password: string;
  };
}

/**
 * Playwright Test with TD-SKU-BEVERAGE-001 Fixture
 *
 * Usage:
 * ```typescript
 * import { test } from './fixtures/testdata/testdata-TD-SKU-BEVERAGE-001.fixture';
 *
 * test('创建饮品SKU', async ({ page, TD_SKU_BEVERAGE_001 }) => {
 *   await page.fill('input[name="skuCode"]', TD_SKU_BEVERAGE_001.skuCode);
 *   await page.fill('input[name="skuName"]', TD_SKU_BEVERAGE_001.skuName);
 *   // ...
 * });
 * ```
 */
export const test = base.extend<{ TD_SKU_BEVERAGE_001: TD_SKU_BEVERAGE_001_Data }>({
  TD_SKU_BEVERAGE_001: [
    async ({}, use) => {
      // ========== Setup: Load seed data ==========
      const seedPath = path.join(process.cwd(), 'testdata/seeds/beverage-skus.json');

      // Read and parse seed file
      const seedContent = fs.readFileSync(seedPath, 'utf-8');
      const seedData = JSON.parse(seedContent);

      // Find the specific seed item by key
      const beverageData = seedData.find((item: any) => item.key === 'mojito-cocktail');

      if (!beverageData) {
        throw new Error(
          'Seed key "mojito-cocktail" not found in testdata/seeds/beverage-skus.json'
        );
      }

      // Map seed data to fixture interface
      const fixtureData: TD_SKU_BEVERAGE_001_Data = {
        skuCode: beverageData.code,
        skuName: beverageData.name,
        skuType: beverageData.type,
        categoryPath: beverageData.category,
        price: beverageData.price,
        unit: beverageData.unit,
        status: beverageData.status,
        adminCredentials: {
          username: beverageData.admin_credentials.username,
          password: beverageData.admin_credentials.password,
        },
      };

      // Provide fixture data to test
      await use(fixtureData);

      // ========== Teardown ==========
      // No teardown needed for seed strategy
      // Seed data is static and doesn't require cleanup
    },
    { scope: 'test' },
  ], // 每个测试独立加载数据
});

export { expect } from '@playwright/test';
