/**
 * @spec P005-bom-inventory-deduction
 * API Response Type Definitions
 *
 * Purpose: TypeScript types for standardized API responses
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

/**
 * Standard API Response format
 * All backend endpoints return this structure
 *
 * @template T - Type of the data payload
 */
export interface ApiResponse<T> {
  /**
   * Indicates if request was successful
   */
  success: boolean;

  /**
   * Response data (only present if success = true)
   */
  data?: T;

  /**
   * Error code (only present if success = false)
   * Format: <MODULE>_<CATEGORY>_<NUMBER>
   * Example: "INV_BIZ_001"
   */
  error?: string;

  /**
   * Human-readable message
   */
  message?: string;

  /**
   * Additional error/response details
   */
  details?: Record<string, any>;

  /**
   * Server timestamp (ISO 8601)
   */
  timestamp: string;
}

/**
 * List/Paginated Response format
 * Used for queries that return multiple records
 *
 * @template T - Type of items in the data array
 */
export interface ListResponse<T> {
  /**
   * Indicates if request was successful
   */
  success: boolean;

  /**
   * Array of result items
   */
  data: T[];

  /**
   * Total count of records (all pages)
   */
  total: number;

  /**
   * Current page number (1-indexed)
   */
  page: number;

  /**
   * Page size
   */
  pageSize: number;

  /**
   * Response message
   */
  message?: string;

  /**
   * Server timestamp (ISO 8601)
   */
  timestamp: string;
}

/**
 * Error Response format
 * Structure for error responses
 */
export interface ErrorResponse {
  /**
   * Always false for error responses
   */
  success: false;

  /**
   * Error code
   * Format: <MODULE>_<CATEGORY>_<NUMBER>
   */
  error: string;

  /**
   * Human-readable error message
   */
  message: string;

  /**
   * Additional error details
   */
  details?: Record<string, any>;

  /**
   * Server timestamp (ISO 8601)
   */
  timestamp: string;
}

/**
 * Inventory shortage details (for INV_BIZ_001 error)
 */
export interface InventoryShortage {
  skuId: string;
  skuName: string;
  available: number;
  required: number;
  shortage: number;
  unit: string;
}

/**
 * Insufficient Inventory Error Response
 * Error code: INV_BIZ_001
 */
export interface InsufficientInventoryError extends ErrorResponse {
  error: 'INV_BIZ_001';
  details: {
    shortages: InventoryShortage[];
  };
}

/**
 * Generic API error class
 */
export class ApiError extends Error {
  constructor(
    public code: string,
    public message: string,
    public details?: Record<string, any>,
    public httpStatus?: number
  ) {
    super(message);
    this.name = 'ApiError';
  }

  /**
   * Create ApiError from error response
   */
  static fromResponse(response: ErrorResponse, httpStatus?: number): ApiError {
    return new ApiError(
      response.error,
      response.message,
      response.details,
      httpStatus
    );
  }
}
