/**
 * @spec P005-bom-inventory-deduction
 * BOM Snapshot Service
 *
 * Purpose: Creates and manages BOM formula snapshots for version locking
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.service;

import com.cinema.hallstore.domain.BomComponent;
import com.cinema.inventory.entity.BomSnapshot;
import com.cinema.inventory.repository.BomSnapshotRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

/**
 * BOM Snapshot Service
 *
 * Creates multi-row snapshots of BOM formulas at order creation time.
 * Ensures deduction uses the same formula even if BOM is modified later.
 *
 * Note: Uses V054 multi-row structure (finished_sku_id + raw_material_sku_id)
 * instead of V059 JSONB snapshot structure.
 */
@Service
public class BomSnapshotService {

    private static final Logger logger = LoggerFactory.getLogger(BomSnapshotService.class);

    private final BomSnapshotRepository bomSnapshotRepository;
    private final BomExpansionService bomExpansionService;

    public BomSnapshotService(
            BomSnapshotRepository bomSnapshotRepository,
            BomExpansionService bomExpansionService
    ) {
        this.bomSnapshotRepository = bomSnapshotRepository;
        this.bomExpansionService = bomExpansionService;
    }

    /**
     * Create BOM snapshots for a finished product SKU
     *
     * V054 multi-row structure: Creates one row per raw material component
     *
     * @param orderId Order ID
     * @param finishedSkuId Finished product SKU ID
     * @return List of created BOM snapshot rows
     */
    @Transactional
    public List<BomSnapshot> createSnapshot(UUID orderId, UUID finishedSkuId) {
        logger.debug("Creating BOM snapshot for order: {}, SKU: {}", orderId, finishedSkuId);

        // Get current BOM formula (only direct components, not expanded)
        List<BomComponent> components = bomExpansionService.getBomFormula(finishedSkuId);

        if (components == null || components.isEmpty()) {
            logger.warn("No BOM components found for SKU: {}. No snapshots created.", finishedSkuId);
            return Collections.emptyList();
        }

        // Create one snapshot row per component (V054 multi-row structure)
        List<BomSnapshot> snapshots = new ArrayList<>();

        for (BomComponent component : components) {
            BomSnapshot snapshot = new BomSnapshot();
            snapshot.setOrderId(orderId);
            snapshot.setSkuId(finishedSkuId);  // Maps to finished_sku_id column
            snapshot.setRawMaterialSkuId(component.getComponentId());
            snapshot.setQuantity(component.getQuantity());
            snapshot.setUnit(component.getUnit());
            snapshot.setBomLevel(0); // V054 table structure - direct components are level 0

            BomSnapshot saved = bomSnapshotRepository.save(snapshot);
            snapshots.add(saved);

            logger.debug("Created BOM snapshot row: order={}, finished={}, raw={}, qty={}{}",
                    orderId, finishedSkuId, component.getComponentId(),
                    component.getQuantity(), component.getUnit());
        }

        logger.info("Created {} BOM snapshot rows for order: {}, SKU: {}",
                snapshots.size(), orderId, finishedSkuId);

        return snapshots;
    }

    /**
     * Create BOM snapshots for multiple order items
     *
     * @param orderId Order ID
     * @param finishedSkuIds List of finished product SKU IDs
     * @return List of all created snapshot rows
     */
    @Transactional
    public List<BomSnapshot> createSnapshots(UUID orderId, List<UUID> finishedSkuIds) {
        List<BomSnapshot> allSnapshots = new ArrayList<>();

        for (UUID finishedSkuId : finishedSkuIds) {
            List<BomSnapshot> snapshotsForSku = createSnapshot(orderId, finishedSkuId);
            allSnapshots.addAll(snapshotsForSku);
        }

        logger.info("Created {} BOM snapshot rows for order: {} ({} SKUs)",
                allSnapshots.size(), orderId, finishedSkuIds.size());
        return allSnapshots;
    }

    /**
     * Get BOM snapshots for an order
     *
     * @param orderId Order ID
     * @return List of BOM snapshot rows
     */
    public List<BomSnapshot> getSnapshotsByOrderId(UUID orderId) {
        return bomSnapshotRepository.findByOrderId(orderId);
    }

    /**
     * Get BOM snapshots for a specific order and finished SKU
     *
     * @param orderId Order ID
     * @param finishedSkuId Finished product SKU ID
     * @return List of BOM snapshot rows for this SKU
     */
    public List<BomSnapshot> getSnapshotsByOrderIdAndSkuId(UUID orderId, UUID finishedSkuId) {
        List<BomSnapshot> allSnapshots = bomSnapshotRepository.findByOrderId(orderId);
        List<BomSnapshot> filtered = new ArrayList<>();

        for (BomSnapshot snapshot : allSnapshots) {
            if (snapshot.getSkuId().equals(finishedSkuId)) {
                filtered.add(snapshot);
            }
        }

        return filtered;
    }
}
