/**
 * @spec P005-bom-inventory-deduction
 * InventoryTransaction Query Service
 *
 * Purpose: Handles querying and filtering of inventory transaction logs
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.service;

import com.cinema.inventory.dto.InventoryTransactionDTO;
import com.cinema.inventory.dto.TransactionQueryRequest;
import com.cinema.inventory.entity.BomSnapshot;
import com.cinema.inventory.entity.InventoryTransaction;
import com.cinema.inventory.repository.BomSnapshotRepository;
import com.cinema.inventory.repository.InventoryTransactionJpaRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import jakarta.persistence.criteria.Predicate;
import java.math.BigDecimal;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Inventory Transaction Query Service
 *
 * Provides advanced querying and filtering capabilities for transaction logs.
 * Supports:
 * - Dynamic filtering by type, SKU, date range, order ID
 * - Pagination and sorting
 * - BOM component detail retrieval
 */
@Service
public class InventoryTransactionService {

    private static final Logger logger = LoggerFactory.getLogger(InventoryTransactionService.class);

    private final InventoryTransactionJpaRepository transactionRepository;
    private final BomSnapshotRepository bomSnapshotRepository;

    public InventoryTransactionService(
            InventoryTransactionJpaRepository transactionRepository,
            BomSnapshotRepository bomSnapshotRepository
    ) {
        this.transactionRepository = transactionRepository;
        this.bomSnapshotRepository = bomSnapshotRepository;
    }

    /**
     * Query transactions with dynamic filters and pagination
     *
     * @param request Query request with filters
     * @return Page of transaction DTOs
     */
    public Page<InventoryTransactionDTO> queryTransactions(TransactionQueryRequest request) {
        logger.debug("Querying transactions with filters: type={}, skuId={}, orderId={}, dateRange=[{}, {}]",
                request.getTransactionType(), request.getSkuId(), request.getOrderId(),
                request.getStartDate(), request.getEndDate());

        // Build specification
        Specification<InventoryTransaction> spec = buildSpecification(request);

        // Build pageable
        Pageable pageable = buildPageable(request);

        // Execute query
        Page<InventoryTransaction> page = transactionRepository.findAll(spec, pageable);

        // Map to DTOs
        Page<InventoryTransactionDTO> dtoPage = page.map(this::mapToDTO);

        logger.debug("Found {} transactions (page {}/{})",
                page.getTotalElements(), page.getNumber() + 1, page.getTotalPages());

        return dtoPage;
    }

    /**
     * Get transaction by ID with BOM component details
     *
     * @param transactionId Transaction ID
     * @return Transaction DTO with BOM components
     */
    public Optional<InventoryTransactionDTO> getTransactionById(UUID transactionId) {
        logger.debug("Fetching transaction detail: {}", transactionId);

        Optional<InventoryTransaction> transactionOpt = transactionRepository.findById(transactionId);

        if (transactionOpt.isEmpty()) {
            logger.warn("Transaction not found: {}", transactionId);
            return Optional.empty();
        }

        InventoryTransaction transaction = transactionOpt.get();
        InventoryTransactionDTO dto = mapToDTO(transaction);

        // Load BOM components if BOM snapshot exists
        if (transaction.getBomSnapshotId() != null) {
            List<InventoryTransactionDTO.BomComponentDTO> components =
                    loadBomComponents(transaction.getBomSnapshotId());
            dto.setBomComponents(components);
        }

        return Optional.of(dto);
    }

    /**
     * Build JPA Specification from query request
     *
     * Dynamically constructs WHERE clause based on provided filters
     */
    private Specification<InventoryTransaction> buildSpecification(TransactionQueryRequest request) {
        return (root, query, criteriaBuilder) -> {
            List<Predicate> predicates = new ArrayList<>();

            // Filter by transaction type
            if (request.getTransactionType() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("transactionType"), request.getTransactionType()
                ));
            }

            // Filter by SKU ID
            if (request.getSkuId() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("skuId"), request.getSkuId()
                ));
            }

            // Filter by order ID
            if (request.getOrderId() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("relatedOrderId"), request.getOrderId()
                ));
            }

            // Filter by store ID
            if (request.getStoreId() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("storeId"), request.getStoreId()
                ));
            }

            // Filter by date range
            if (request.getStartDate() != null) {
                predicates.add(criteriaBuilder.greaterThanOrEqualTo(
                        root.get("operatedAt"), request.getStartDate()
                ));
            }

            if (request.getEndDate() != null) {
                predicates.add(criteriaBuilder.lessThanOrEqualTo(
                        root.get("operatedAt"), request.getEndDate()
                ));
            }

            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
        };
    }

    /**
     * Build Pageable from query request
     */
    private Pageable buildPageable(TransactionQueryRequest request) {
        Sort.Direction direction = "ASC".equalsIgnoreCase(request.getSortDirection())
                ? Sort.Direction.ASC
                : Sort.Direction.DESC;

        Sort sort = Sort.by(direction, request.getSortBy());

        return PageRequest.of(
                request.getPage() != null ? request.getPage() : 0,
                request.getPageSize() != null ? request.getPageSize() : 20,
                sort
        );
    }

    /**
     * Map InventoryTransaction entity to DTO
     */
    private InventoryTransactionDTO mapToDTO(InventoryTransaction transaction) {
        InventoryTransactionDTO dto = new InventoryTransactionDTO();
        dto.setId(transaction.getId());
        dto.setStoreId(transaction.getStoreId());
        dto.setStoreName("Store-" + transaction.getStoreId()); // TODO: Get actual store name
        dto.setSkuId(transaction.getSkuId());
        dto.setSkuName("SKU-" + transaction.getSkuId()); // TODO: Get actual SKU name
        dto.setTransactionType(transaction.getTransactionType());
        dto.setQuantity(transaction.getQuantity());
        dto.setQuantityBefore(transaction.getQuantityBefore());
        dto.setQuantityAfter(transaction.getQuantityAfter());
        dto.setRelatedOrderId(transaction.getRelatedOrderId());
        dto.setOrderNumber(transaction.getRelatedOrderId() != null
                ? "ORD-" + transaction.getRelatedOrderId().toString().substring(0, 8)
                : null);
        dto.setBomSnapshotId(transaction.getBomSnapshotId());
        dto.setAdjustmentReasonId(transaction.getAdjustmentReasonId());
        dto.setOperatorId(transaction.getOperatorId());
        dto.setOperatorName("Operator-" + transaction.getOperatorId()); // TODO: Get actual operator name
        dto.setOperatedAt(transaction.getOperatedAt());
        dto.setNotes(transaction.getNotes());
        dto.setCreatedAt(transaction.getCreatedAt());

        return dto;
    }

    /**
     * Load BOM components from snapshot (V054 multi-row structure)
     *
     * Steps:
     * 1. Get the snapshot row by ID to extract orderId and finishedSkuId
     * 2. Query all snapshot rows for that order+SKU combination
     * 3. Map each row to a component DTO
     */
    private List<InventoryTransactionDTO.BomComponentDTO> loadBomComponents(UUID bomSnapshotId) {
        // Step 1: Get the first snapshot row to extract orderId and finishedSkuId
        Optional<BomSnapshot> firstSnapshotOpt = bomSnapshotRepository.findById(bomSnapshotId);

        if (firstSnapshotOpt.isEmpty()) {
            logger.warn("BOM snapshot not found: {}", bomSnapshotId);
            return Collections.emptyList();
        }

        BomSnapshot firstSnapshot = firstSnapshotOpt.get();
        UUID orderId = firstSnapshot.getOrderId();
        UUID finishedSkuId = firstSnapshot.getSkuId(); // Maps to finished_sku_id

        // Step 2: Query all snapshot rows for this order+SKU (V054 multi-row structure)
        List<BomSnapshot> allSnapshots = bomSnapshotRepository.findByOrderIdAndSkuId(orderId, finishedSkuId);

        if (allSnapshots.isEmpty()) {
            logger.warn("No BOM snapshots found for order: {}, SKU: {}", orderId, finishedSkuId);
            return Collections.emptyList();
        }

        // Step 3: Map each snapshot row to component DTO
        return allSnapshots.stream()
                .map(this::mapSnapshotToComponentDTO)
                .collect(Collectors.toList());
    }

    /**
     * Map BomSnapshot entity to BomComponentDTO (V054 multi-row structure)
     */
    private InventoryTransactionDTO.BomComponentDTO mapSnapshotToComponentDTO(BomSnapshot snapshot) {
        InventoryTransactionDTO.BomComponentDTO dto = new InventoryTransactionDTO.BomComponentDTO();

        // V054 structure: each row has finished_sku_id, raw_material_sku_id, quantity, unit
        dto.setComponentSkuId(snapshot.getRawMaterialSkuId());
        dto.setComponentSkuName("Component-" + snapshot.getRawMaterialSkuId()); // TODO: Get actual name from SKUs table
        dto.setStandardQuantity(snapshot.getQuantity());
        dto.setUnit(snapshot.getUnit());

        // V054 table doesn't have these fields, set defaults
        dto.setUnitCost(BigDecimal.ZERO); // TODO: Query from SKUs table or inventory
        dto.setIsOptional(false); // V054 doesn't track this
        dto.setWastageRate(BigDecimal.ZERO); // V054 doesn't have wastage_rate column
        dto.setActualQuantity(snapshot.getQuantity()); // No wastage, so actual = standard

        return dto;
    }
}
