/**
 * @spec O012-order-inventory-reservation
 * Reservation Query Service
 *
 * Purpose: 查询库存预占记录,支持多维度筛选和分页
 * Provides: 审计追踪和库存预占历史查询功能
 *
 * Author: Generated by O012 spec
 * Date: 2026-01-14
 */

package com.cinema.inventory.service;

import com.cinema.inventory.entity.InventoryReservation;
import com.cinema.inventory.entity.InventoryReservation.ReservationStatus;
import com.cinema.inventory.repository.InventoryReservationRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.UUID;

/**
 * 预占记录查询服务
 *
 * 功能:
 * 1. 按订单号、门店ID、SKU ID、状态、时间范围查询预占记录
 * 2. 支持分页查询 (默认pageSize=20, 最大100)
 * 3. 按创建时间降序排序 (最新记录在前)
 *
 * 查询维度:
 * - orderId: 订单ID
 * - storeId: 门店ID
 * - skuId: SKU ID
 * - status: 预占状态 (ACTIVE, RELEASED, EXPIRED, CANCELLED)
 * - startTime/endTime: 创建时间范围
 *
 * 性能目标:
 * - 查询响应时间 < 500ms (数据量1万条以内)
 * - 支持并发查询
 */
@Service
public class ReservationQueryService {

    private static final Logger logger = LoggerFactory.getLogger(ReservationQueryService.class);

    private static final int DEFAULT_PAGE_SIZE = 20;
    private static final int MAX_PAGE_SIZE = 100;

    private final InventoryReservationRepository reservationRepository;

    public ReservationQueryService(InventoryReservationRepository reservationRepository) {
        this.reservationRepository = reservationRepository;
    }

    /**
     * 按订单ID查询预占记录
     *
     * @param orderId 订单ID
     * @param page 页码 (从0开始)
     * @param pageSize 每页数量 (默认20, 最大100)
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryByOrderId(UUID orderId, int page, Integer pageSize) {
        logger.info("查询订单预占记录: orderId={}, page={}, pageSize={}", orderId, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository.findByOrderId(orderId, pageable);

        logger.info("查询完成: orderId={}, totalElements={}, totalPages={}", 
                orderId, result.getTotalElements(), result.getTotalPages());

        return result;
    }

    /**
     * 按门店ID查询预占记录
     *
     * @param storeId 门店ID
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryByStoreId(UUID storeId, int page, Integer pageSize) {
        logger.info("查询门店预占记录: storeId={}, page={}, pageSize={}", storeId, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository.findByStoreId(storeId, pageable);

        logger.info("查询完成: storeId={}, totalElements={}", storeId, result.getTotalElements());

        return result;
    }

    /**
     * 按SKU ID查询预占记录
     *
     * @param skuId SKU ID
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryBySkuId(UUID skuId, int page, Integer pageSize) {
        logger.info("查询SKU预占记录: skuId={}, page={}, pageSize={}", skuId, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository.findBySkuId(skuId, pageable);

        logger.info("查询完成: skuId={}, totalElements={}", skuId, result.getTotalElements());

        return result;
    }

    /**
     * 按状态查询预占记录
     *
     * @param status 预占状态
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryByStatus(ReservationStatus status, int page, Integer pageSize) {
        logger.info("查询预占记录(按状态): status={}, page={}, pageSize={}", status, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository.findByStatus(status, pageable);

        logger.info("查询完成: status={}, totalElements={}", status, result.getTotalElements());

        return result;
    }

    /**
     * 按时间范围查询预占记录
     *
     * @param startTime 开始时间 (包含)
     * @param endTime 结束时间 (包含)
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryByTimeRange(
            Instant startTime,
            Instant endTime,
            int page,
            Integer pageSize
    ) {
        logger.info("查询预占记录(按时间范围): startTime={}, endTime={}, page={}, pageSize={}", 
                startTime, endTime, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository
                .findByCreatedAtBetween(startTime, endTime, pageable);

        logger.info("查询完成: timeRange=[{}, {}], totalElements={}", 
                startTime, endTime, result.getTotalElements());

        return result;
    }

    /**
     * 组合查询: 按门店ID和状态
     *
     * @param storeId 门店ID
     * @param status 预占状态
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    public Page<InventoryReservation> queryByStoreAndStatus(
            UUID storeId,
            ReservationStatus status,
            int page,
            Integer pageSize
    ) {
        logger.info("查询预占记录(门店+状态): storeId={}, status={}, page={}, pageSize={}", 
                storeId, status, page, pageSize);

        Pageable pageable = createPageable(page, pageSize);
        Page<InventoryReservation> result = reservationRepository
                .findByStoreIdAndStatus(storeId, status, pageable);

        logger.info("查询完成: storeId={}, status={}, totalElements={}", 
                storeId, status, result.getTotalElements());

        return result;
    }

    /**
     * 创建分页对象
     * 
     * 规则:
     * - 默认pageSize=20
     * - 最大pageSize=100
     * - 按创建时间降序排序 (最新记录在前)
     *
     * @param page 页码 (从0开始)
     * @param pageSize 每页数量 (null时使用默认值)
     * @return Pageable对象
     */
    private Pageable createPageable(int page, Integer pageSize) {
        int size = (pageSize == null) ? DEFAULT_PAGE_SIZE : Math.min(pageSize, MAX_PAGE_SIZE);
        
        if (pageSize != null && pageSize > MAX_PAGE_SIZE) {
            logger.warn("请求的pageSize({})超过最大值({}), 已自动调整", pageSize, MAX_PAGE_SIZE);
        }

        return PageRequest.of(
                page,
                size,
                Sort.by(Sort.Direction.DESC, "createdAt")
        );
    }
}
