openapi: 3.0.3
info:
  title: 门店管理 CRUD API
  version: 1.0.0
  description: 门店管理增删改功能的REST API接口规范
servers:
  - url: http://localhost:8080/api
    description: 本地开发环境
paths:
  /stores:
    post:
      summary: 创建新门店
      operationId: createStore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStoreDTO'
      responses:
        '201':
          description: 门店创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Store'
        '400':
          $ref: '#/components/responses/ValidationError'
        '409':
          $ref: '#/components/responses/ConflictError'

  /stores/{id}:
    put:
      summary: 更新门店信息
      operationId: updateStore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStoreDTO'
      responses:
        '200':
          description: 门店更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Store'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
    
    delete:
      summary: 删除门店
      operationId: deleteStore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 门店删除成功
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/DependencyError'

  /stores/{id}/status:
    patch:
      summary: 切换门店状态
      operationId: toggleStoreStatus
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [ACTIVE, INACTIVE]
              required: [status]
      responses:
        '200':
          description: 状态切换成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Store'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  schemas:
    Store:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        region:
          type: string
        city:
          type: string
        province:
          type: string
          nullable: true
        district:
          type: string
          nullable: true
        address:
          type: string
        phone:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateStoreDTO:
      type: object
      required: [name, region, city, address, phone]
      properties:
        name:
          type: string
          maxLength: 100
        region:
          type: string
        city:
          type: string
        province:
          type: string
        district:
          type: string
        address:
          type: string
        phone:
          type: string
          pattern: '^(1[3-9]\d{9}|0\d{2,3}-\d{7,8})$'

    UpdateStoreDTO:
      type: object
      required: [version]
      properties:
        name:
          type: string
          maxLength: 100
        region:
          type: string
        city:
          type: string
        province:
          type: string
        district:
          type: string
        address:
          type: string
        phone:
          type: string
          pattern: '^(1[3-9]\d{9}|0\d{2,3}-\d{7,8})$'
        version:
          type: integer
          description: 乐观锁版本号

    ApiResponse_Store:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/Store'
        timestamp:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        details:
          type: object
        timestamp:
          type: string
          format: date-time

  responses:
    ValidationError:
      description: 请求参数验证失败
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ConflictError:
      description: 资源冲突(如门店名称重复或版本冲突)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFoundError:
      description: 门店不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    DependencyError:
      description: 门店有依赖关系无法删除
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
