/**
 * @spec P005-bom-inventory-deduction
 * InventoryDeduction Controller
 *
 * Purpose: REST API endpoints for inventory deduction operations
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.controller;

import com.cinema.inventory.dto.DeductionRequest;
import com.cinema.inventory.dto.DeductionResponse;
import com.cinema.inventory.service.InventoryDeductionService;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Inventory Deduction Controller
 *
 * Endpoints:
 * - POST /api/inventory/deductions - Deduct inventory for fulfilled order
 */
@RestController
@RequestMapping("/api/inventory/deductions")
public class InventoryDeductionController {

    private static final Logger logger = LoggerFactory.getLogger(InventoryDeductionController.class);

    private final InventoryDeductionService deductionService;

    public InventoryDeductionController(InventoryDeductionService deductionService) {
        this.deductionService = deductionService;
    }

    /**
     * Deduct inventory for fulfilled order
     *
     * POST /api/inventory/deductions
     *
     * This endpoint is called when an order is fulfilled (出品确认).
     * It will:
     * 1. Load BOM snapshots from reservation time
     * 2. Deduct on_hand_qty
     * 3. Release reserved_qty
     * 4. Generate transaction logs
     * 5. Mark reservations as FULFILLED
     *
     * @param request Deduction request
     * @return Deduction response with deducted components
     */
    @PostMapping
    public ResponseEntity<ApiResponse<DeductionResponse>> deductInventory(
            @Valid @RequestBody DeductionRequest request
    ) {
        logger.info("Received deduction request for order: {}", request.getOrderId());

        // Call service
        List<InventoryDeductionService.DeductedMaterial> deductedMaterials =
                deductionService.deductInventory(request.getOrderId(), request.getStoreId());

        // Build response
        List<DeductionResponse.DeductedComponent> components = deductedMaterials.stream()
                .map(m -> new DeductionResponse.DeductedComponent(
                        m.getSkuId(),
                        m.getSkuName(),
                        m.getQuantity(),
                        m.getUnit()
                ))
                .collect(Collectors.toList());

        DeductionResponse data = new DeductionResponse(request.getOrderId(), components);

        ApiResponse<DeductionResponse> response = new ApiResponse<>(
                true,
                data,
                null,
                "Deduction successful",
                null,
                Instant.now().toString()
        );

        logger.info("Deduction successful for order: {}. Deducted {} components",
                request.getOrderId(), components.size());

        return ResponseEntity.ok(response);
    }

    /**
     * API Response wrapper
     */
    public record ApiResponse<T>(
            boolean success,
            T data,
            String error,
            String message,
            java.util.Map<String, Object> details,
            String timestamp
    ) {
    }
}
