/**
 * @spec O012-order-inventory-reservation
 * Reservation Controller - 库存预占记录查询接口
 *
 * Purpose: 提供库存预占记录的查询REST API
 * Provides: 审计追踪和历史记录查询功能
 *
 * Author: Generated by O012 spec
 * Date: 2026-01-14
 */

package com.cinema.inventory.controller;

import com.cinema.common.dto.ApiResponse;
import com.cinema.inventory.entity.InventoryReservation;
import com.cinema.inventory.entity.InventoryReservation.ReservationStatus;
import com.cinema.inventory.service.ReservationQueryService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.UUID;

/**
 * 预占记录查询控制器 - B端API
 *
 * 提供库存预占记录的查询功能,支持多维度筛选:
 * - 按订单号查询
 * - 按门店ID查询
 * - 按SKU ID查询
 * - 按状态查询
 * - 按时间范围查询
 * - 组合查询 (门店+状态)
 */
@RestController
@RequestMapping("/api/admin/inventory/reservations")
@CrossOrigin(origins = "*")
public class InventoryReservationController {

    private static final Logger logger = LoggerFactory.getLogger(InventoryReservationController.class);

    private final ReservationQueryService queryService;

    public InventoryReservationController(ReservationQueryService queryService) {
        this.queryService = queryService;
    }

    /**
     * 按订单ID查询预占记录
     *
     * GET /api/admin/inventory/reservations/by-order/{orderId}
     *
     * @param orderId 订单ID
     * @param page 页码 (从0开始, 默认0)
     * @param pageSize 每页数量 (默认20, 最大100)
     * @return 预占记录分页结果
     */
    @GetMapping("/by-order/{orderId}")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryByOrderId(
            @PathVariable String orderId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询订单预占记录: orderId={}, page={}, pageSize={}", orderId, page, pageSize);

        UUID orderIdParsed = UUID.fromString(orderId);
        Page<InventoryReservation> result = queryService.queryByOrderId(orderIdParsed, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }

    /**
     * 按门店ID查询预占记录
     *
     * GET /api/admin/inventory/reservations/by-store/{storeId}
     *
     * @param storeId 门店ID
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    @GetMapping("/by-store/{storeId}")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryByStoreId(
            @PathVariable String storeId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询门店预占记录: storeId={}, page={}, pageSize={}", storeId, page, pageSize);

        UUID storeIdParsed = UUID.fromString(storeId);
        Page<InventoryReservation> result = queryService.queryByStoreId(storeIdParsed, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }

    /**
     * 按SKU ID查询预占记录
     *
     * GET /api/admin/inventory/reservations/by-sku/{skuId}
     *
     * @param skuId SKU ID
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    @GetMapping("/by-sku/{skuId}")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryBySkuId(
            @PathVariable String skuId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询SKU预占记录: skuId={}, page={}, pageSize={}", skuId, page, pageSize);

        UUID skuIdParsed = UUID.fromString(skuId);
        Page<InventoryReservation> result = queryService.queryBySkuId(skuIdParsed, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }

    /**
     * 按状态查询预占记录
     *
     * GET /api/admin/inventory/reservations/by-status/{status}
     *
     * @param status 预占状态 (ACTIVE, RELEASED, EXPIRED, CANCELLED)
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    @GetMapping("/by-status/{status}")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryByStatus(
            @PathVariable String status,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询预占记录(按状态): status={}, page={}, pageSize={}", status, page, pageSize);

        ReservationStatus statusEnum = ReservationStatus.valueOf(status.toUpperCase());
        Page<InventoryReservation> result = queryService.queryByStatus(statusEnum, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }

    /**
     * 按时间范围查询预占记录
     *
     * GET /api/admin/inventory/reservations/by-time
     *
     * @param startTime 开始时间 (ISO 8601格式, 例: 2026-01-14T00:00:00Z)
     * @param endTime 结束时间 (ISO 8601格式)
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    @GetMapping("/by-time")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryByTimeRange(
            @RequestParam String startTime,
            @RequestParam String endTime,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询预占记录(按时间范围): startTime={}, endTime={}, page={}, pageSize={}", 
                startTime, endTime, page, pageSize);

        Instant start = Instant.parse(startTime);
        Instant end = Instant.parse(endTime);
        Page<InventoryReservation> result = queryService.queryByTimeRange(start, end, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }

    /**
     * 组合查询: 按门店ID和状态
     *
     * GET /api/admin/inventory/reservations/by-store-status
     *
     * @param storeId 门店ID
     * @param status 预占状态
     * @param page 页码
     * @param pageSize 每页数量
     * @return 预占记录分页结果
     */
    @GetMapping("/by-store-status")
    public ResponseEntity<ApiResponse<Page<InventoryReservation>>> queryByStoreAndStatus(
            @RequestParam String storeId,
            @RequestParam String status,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(required = false) Integer pageSize
    ) {
        logger.info("查询预占记录(门店+状态): storeId={}, status={}, page={}, pageSize={}", 
                storeId, status, page, pageSize);

        UUID storeIdParsed = UUID.fromString(storeId);
        ReservationStatus statusEnum = ReservationStatus.valueOf(status.toUpperCase());
        Page<InventoryReservation> result = queryService
                .queryByStoreAndStatus(storeIdParsed, statusEnum, page, pageSize);

        return ResponseEntity.ok(ApiResponse.success(result));
    }
}
