/**
 * @spec P005-bom-inventory-deduction
 * InventoryTransaction Controller
 *
 * Purpose: REST API endpoints for querying inventory transaction logs
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.controller;

import com.cinema.inventory.dto.InventoryTransactionDTO;
import com.cinema.inventory.dto.TransactionQueryRequest;
import com.cinema.inventory.entity.InventoryTransaction;
import com.cinema.inventory.service.InventoryTransactionService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * Inventory Transaction Controller
 *
 * Endpoints:
 * - GET /api/inventory/transactions - Query transaction logs with filters
 * - GET /api/inventory/transactions/{id} - Get transaction detail with BOM components
 */
@RestController
@RequestMapping("/api/inventory/transactions")
public class InventoryTransactionController {

    private static final Logger logger = LoggerFactory.getLogger(InventoryTransactionController.class);

    private final InventoryTransactionService transactionService;

    public InventoryTransactionController(InventoryTransactionService transactionService) {
        this.transactionService = transactionService;
    }

    /**
     * Query transaction logs with filters and pagination
     *
     * GET /api/inventory/transactions?transactionType=BOM_DEDUCTION&page=0&pageSize=20
     *
     * Supported filters:
     * - transactionType: Transaction type enum
     * - skuId: UUID
     * - orderId: UUID
     * - storeId: UUID
     * - startDate: ISO-8601 datetime
     * - endDate: ISO-8601 datetime
     * - page: Page number (0-indexed)
     * - pageSize: Page size (default 20)
     * - sortBy: Field to sort by (default "operatedAt")
     * - sortDirection: ASC or DESC (default DESC)
     *
     * @return Paginated list of transactions
     */
    @GetMapping
    public ResponseEntity<Page<InventoryTransactionDTO>> queryTransactions(
            @RequestParam(required = false) InventoryTransaction.TransactionType transactionType,
            @RequestParam(required = false) UUID skuId,
            @RequestParam(required = false) UUID orderId,
            @RequestParam(required = false) UUID storeId,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant startDate,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant endDate,
            @RequestParam(defaultValue = "0") Integer page,
            @RequestParam(defaultValue = "20") Integer pageSize,
            @RequestParam(defaultValue = "operatedAt") String sortBy,
            @RequestParam(defaultValue = "DESC") String sortDirection
    ) {
        logger.info("GET /api/inventory/transactions - Querying transaction logs");

        // Build request
        TransactionQueryRequest request = new TransactionQueryRequest();
        request.setTransactionType(transactionType);
        request.setSkuId(skuId);
        request.setOrderId(orderId);
        request.setStoreId(storeId);
        request.setStartDate(startDate);
        request.setEndDate(endDate);
        request.setPage(page);
        request.setPageSize(pageSize);
        request.setSortBy(sortBy);
        request.setSortDirection(sortDirection);

        // Query transactions
        Page<InventoryTransactionDTO> result = transactionService.queryTransactions(request);

        logger.info("Found {} transactions (page {}/{})",
                result.getTotalElements(), result.getNumber() + 1, result.getTotalPages());

        return ResponseEntity.ok(result);
    }

    /**
     * Get transaction detail by ID with BOM components
     *
     * GET /api/inventory/transactions/{id}
     *
     * Returns:
     * - Transaction basic info
     * - BOM component breakdown (if BOM snapshot exists)
     *
     * @param id Transaction ID
     * @return Transaction detail
     */
    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<InventoryTransactionDTO>> getTransactionById(
            @PathVariable UUID id
    ) {
        logger.info("GET /api/inventory/transactions/{} - Fetching transaction detail", id);

        Optional<InventoryTransactionDTO> transactionOpt = transactionService.getTransactionById(id);

        if (transactionOpt.isEmpty()) {
            logger.warn("Transaction not found: {}", id);
            return ResponseEntity.status(404).body(
                    new ApiResponse<>(
                            false,
                            null,
                            "TRANSACTION_NOT_FOUND",
                            "Transaction not found",
                            null,
                            Instant.now().toString()
                    )
            );
        }

        InventoryTransactionDTO transaction = transactionOpt.get();

        ApiResponse<InventoryTransactionDTO> response = new ApiResponse<>(
                true,
                transaction,
                null,
                "Success",
                null,
                Instant.now().toString()
        );

        logger.info("Transaction detail retrieved: {}, BOM components: {}",
                id, transaction.getBomComponents() != null ? transaction.getBomComponents().size() : 0);

        return ResponseEntity.ok(response);
    }

    /**
     * API Response wrapper
     */
    public record ApiResponse<T>(
            boolean success,
            T data,
            String error,
            String message,
            java.util.Map<String, Object> details,
            String timestamp
    ) {
    }
}
