/**
 * @spec P005-bom-inventory-deduction
 * InventoryReservation Controller
 *
 * Purpose: REST API endpoints for inventory reservation operations
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.controller;

import com.cinema.inventory.dto.ReservationRequest;
import com.cinema.inventory.dto.ReservationResponse;
import com.cinema.inventory.dto.ReservationResponse.ReservedComponent;
import com.cinema.inventory.entity.InventoryReservation;
import com.cinema.inventory.service.InventoryReservationService;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Inventory Reservation Controller
 *
 * Endpoints:
 * - POST /api/inventory/reservations - Reserve inventory for order
 * - DELETE /api/inventory/reservations/{orderId} - Release reservation
 */
@RestController
@RequestMapping("/api/inventory/reservations")
public class InventoryReservationController {

    private static final Logger logger = LoggerFactory.getLogger(InventoryReservationController.class);

    private final InventoryReservationService reservationService;

    public InventoryReservationController(InventoryReservationService reservationService) {
        this.reservationService = reservationService;
    }

    /**
     * Reserve inventory for order
     *
     * POST /api/inventory/reservations
     *
     * @param request Reservation request
     * @return Reservation response with reserved components
     */
    @PostMapping
    public ResponseEntity<ApiResponse<ReservationResponse>> reserveInventory(
            @Valid @RequestBody ReservationRequest request
    ) {
        logger.info("Received reservation request for order: {}", request.getOrderId());

        // Convert request items to map
        Map<UUID, java.math.BigDecimal> items = new HashMap<>();
        for (ReservationRequest.OrderItem item : request.getItems()) {
            items.put(item.getSkuId(), item.getQuantity());
        }

        // Call service
        List<InventoryReservation> reservations = reservationService.reserveInventory(
                request.getOrderId(),
                request.getStoreId(),
                items
        );

        // Build response
        List<UUID> reservationIds = reservations.stream()
                .map(InventoryReservation::getId)
                .collect(Collectors.toList());

        List<ReservedComponent> components = reservations.stream()
                .map(r -> new ReservedComponent(
                        r.getSkuId(),
                        extractSkuName(r.getNotes()),
                        r.getReservedQuantity(),
                        extractUnit(r.getNotes())
                ))
                .collect(Collectors.toList());

        ReservationResponse data = new ReservationResponse(
                request.getOrderId(),
                reservationIds,
                components
        );

        ApiResponse<ReservationResponse> response = new ApiResponse<>(
                true,
                data,
                null,
                "Reservation successful",
                null,
                Instant.now().toString()
        );

        logger.info("Reservation successful for order: {}. Reserved {} components",
                request.getOrderId(), components.size());

        return ResponseEntity.ok(response);
    }

    /**
     * Release reservation (cancel order)
     *
     * DELETE /api/inventory/reservations/{orderId}
     *
     * @param orderId Order ID
     * @return Release response
     */
    @DeleteMapping("/{orderId}")
    public ResponseEntity<ApiResponse<Map<String, Object>>> releaseReservation(
            @PathVariable UUID orderId
    ) {
        logger.info("Received release request for order: {}", orderId);

        int releasedCount = reservationService.releaseReservation(orderId);

        Map<String, Object> data = Map.of(
                "orderId", orderId.toString(),
                "releasedReservations", releasedCount
        );

        ApiResponse<Map<String, Object>> response = new ApiResponse<>(
                true,
                data,
                null,
                "Reservation released successfully",
                null,
                Instant.now().toString()
        );

        logger.info("Released {} reservations for order: {}", releasedCount, orderId);
        return ResponseEntity.ok(response);
    }

    /**
     * Extract SKU name from notes (temporary helper)
     * TODO: Improve by fetching actual SKU name from database
     */
    private String extractSkuName(String notes) {
        if (notes == null) return "Unknown";
        int ofIndex = notes.indexOf(" of ");
        if (ofIndex > 0) {
            return notes.substring(ofIndex + 4);
        }
        return "Unknown";
    }

    /**
     * Extract unit from notes (temporary helper)
     */
    private String extractUnit(String notes) {
        if (notes == null) return "unit";
        String[] parts = notes.split(" ");
        if (parts.length > 2) {
            return parts[2];
        }
        return "unit";
    }

    /**
     * API Response wrapper
     */
    public record ApiResponse<T>(
            boolean success,
            T data,
            String error,
            String message,
            Map<String, Object> details,
            String timestamp
    ) {
    }
}
