/**
 * @spec P005-bom-inventory-deduction
 * Spring Boot Transaction Configuration
 *
 * Purpose: Configure transaction isolation level for inventory operations
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.annotation.EnableTransactionManagement;

/**
 * Transaction Configuration
 *
 * Default isolation level: READ_COMMITTED
 * - Prevents dirty reads
 * - Allows concurrent transactions to read committed data
 * - Row-level locking (SELECT FOR UPDATE) used for inventory operations
 *
 * Why READ_COMMITTED over REPEATABLE_READ?
 * - Lower lock overhead for high-concurrency scenarios (100+ orders/sec)
 * - PostgreSQL's MVCC handles most consistency issues
 * - Explicit row-level locks (SELECT FOR UPDATE) provide needed serialization
 * - Reduces likelihood of lock timeouts
 *
 * @see com.cinema.inventory.service.InventoryReservationService
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Configuration
@EnableTransactionManagement
public class TransactionConfig {

    /**
     * Default transaction timeout: 30 seconds
     * Prevents long-running transactions from blocking inventory operations
     */
    public static final int DEFAULT_TRANSACTION_TIMEOUT_SECONDS = 30;

    /**
     * Lock acquisition timeout: 10 seconds
     * Used in SELECT FOR UPDATE queries
     */
    public static final int LOCK_TIMEOUT_SECONDS = 10;
}
