/**
 * @spec T003-e2e-runner
 * Playwright test runner with config generation and execution (T015, T016, T017, T021)
 */

import { spawn } from 'child_process';
import { join } from 'path';
import type { E2ERunConfig, PlaywrightProject } from './schemas';
import { fileExists, ensureDirExists } from './utils/file-utils';
import { TestExecutionError, FileOperationError } from './utils/error-handler';
import { writeFileSync } from 'fs';

/**
 * Playwright configuration type (subset for our needs)
 */
export interface PlaywrightTestConfig {
  use?: {
    baseURL?: string;
    [key: string]: any;
  };
  retries?: number;
  workers?: number;
  timeout?: number;
  testMatch?: string | string[];
  reporter?: any;
  projects?: Array<{
    name: string;
    use?: Record<string, any>;
  }>;
}

/**
 * Validate report directory before test execution (T021)
 * Prevents accidental overwriting of existing reports
 * @param reportDir - Report output directory path
 * @param force - If true, skip validation and allow overwrite
 * @throws FileOperationError if directory exists and force=false
 */
export function validateReportDirectory(
  reportDir: string,
  force: boolean = false
): void {
  if (force) {
    // Skip validation if force flag is set
    return;
  }

  if (fileExists(reportDir)) {
    throw new FileOperationError(
      `Report directory already exists: ${reportDir}\nUse --force flag to overwrite existing reports`,
      { reportDir, force }
    );
  }
}

/**
 * Generate Playwright config object from E2ERunConfig (T015)
 * @param e2eConfig - E2ERunConfig from user
 * @returns PlaywrightTestConfig object
 */
export function generatePlaywrightConfig(
  e2eConfig: E2ERunConfig
): PlaywrightTestConfig {
  const config: PlaywrightTestConfig = {
    use: {
      baseURL: e2eConfig.baseURL,
    },
    retries: e2eConfig.retries,
    timeout: e2eConfig.timeout,
    testMatch: e2eConfig.testMatch,
    reporter: [
      [
        'json',
        {
          outputFile: join(e2eConfig.report_output_dir, 'results.json'),
        },
      ],
      [
        'html',
        {
          outputFolder: join(e2eConfig.report_output_dir, 'html-report'),
          open: 'never',
        },
      ],
      ['list'],
    ],
  };

  // Add workers if specified
  if (e2eConfig.workers !== undefined) {
    config.workers = e2eConfig.workers;
  }

  // Add projects if specified
  if (e2eConfig.projects && e2eConfig.projects.length > 0) {
    config.projects = e2eConfig.projects.map((project: PlaywrightProject) => ({
      name: project.name,
      use: {
        ...project.use,
        baseURL: e2eConfig.baseURL, // Merge baseURL into each project
      },
    }));
  }

  return config;
}

/**
 * Write Playwright config object to TypeScript config file (T016)
 * @param config - PlaywrightTestConfig object
 * @param tempPath - Path to write config file
 */
export function writePlaywrightConfigFile(
  config: PlaywrightTestConfig,
  tempPath: string
): void {
  ensureDirExists(join(tempPath, '..'));

  const configContent = `/**
 * @spec T003-e2e-runner
 * Auto-generated Playwright configuration
 * Generated by e2e-runner skill
 */

import { defineConfig } from '@playwright/test';

export default defineConfig(${JSON.stringify(config, null, 2)});
`;

  writeFileSync(tempPath, configContent, 'utf-8');
}

/**
 * Execute Playwright tests using npx playwright test (T017)
 * @param configPath - Path to Playwright config file
 * @param testMatch - Test file pattern to execute
 * @returns Promise<number> - Exit code from Playwright execution
 * @throws TestExecutionError if config file does not exist or execution fails
 */
export async function executePlaywrightTests(
  configPath: string,
  testMatch: string
): Promise<number> {
  // Validate config file exists
  if (!fileExists(configPath)) {
    throw new TestExecutionError(
      `Playwright config file does not exist: ${configPath}`,
      { configPath }
    );
  }

  return new Promise((resolve, reject) => {
    const playwrightProcess = spawn(
      'npx',
      ['playwright', 'test', '--config', configPath, testMatch],
      {
        stdio: 'inherit', // Pass through stdout/stderr to parent process
        shell: true,
      }
    );

    playwrightProcess.on('close', (code) => {
      if (code === null) {
        reject(
          new TestExecutionError('Playwright process terminated unexpectedly', {
            configPath,
            testMatch,
          })
        );
      } else {
        resolve(code);
      }
    });

    playwrightProcess.on('error', (error) => {
      reject(
        new TestExecutionError(`Failed to execute Playwright: ${error.message}`, {
          configPath,
          testMatch,
          error: error.message,
        })
      );
    });
  });
}
