/**
 * @spec T003-e2e-runner
 * Zod schemas and TypeScript interfaces for E2E Test Runner
 */

import { z } from 'zod';

/**
 * T006: E2ERunConfig Zod Schema
 * Configuration for E2E test execution with Playwright
 */
export const PlaywrightProjectSchema = z.object({
  name: z.string(),
  use: z.record(z.any()).optional(),
});

export const E2ERunConfigSchema = z.object({
  env_profile: z
    .string()
    .regex(/^[a-z0-9-]+$/, {
      message: 'env_profile must be lowercase alphanumeric with hyphens',
    }),
  baseURL: z
    .string()
    .url({ message: 'baseURL must be a valid HTTP/HTTPS URL' })
    .regex(/^https?:\/\//, {
      message: 'baseURL must start with http:// or https://',
    }),
  projects: z.array(PlaywrightProjectSchema).optional(),
  credentials_ref: z.string().optional(),
  retries: z
    .number()
    .int()
    .min(0, { message: 'retries must be >= 0' })
    .max(5, { message: 'retries must be <= 5' })
    .default(0),
  workers: z
    .number()
    .int()
    .min(1, { message: 'workers must be >= 1' })
    .optional(),
  timeout: z
    .number()
    .int()
    .min(1000, { message: 'timeout must be >= 1000ms' })
    .default(30000),
  report_output_dir: z
    .string()
    .min(1, { message: 'report_output_dir cannot be empty' }),
  testMatch: z.string().default('scenarios/**/*.spec.ts'),
});

export type E2ERunConfig = z.infer<typeof E2ERunConfigSchema>;
export type PlaywrightProject = z.infer<typeof PlaywrightProjectSchema>;

/**
 * T007: CredentialsFile Zod Schema
 * Credentials file for secure authentication data
 */
export const UserCredentialSchema = z.object({
  role: z.string(),
  username: z.string(),
  password: z.string().min(1, { message: 'password cannot be empty' }),
  display_name: z.string().optional(),
});

export const ApiKeyCredentialSchema = z.object({
  service: z.string(),
  api_key: z.string().min(1, { message: 'api_key cannot be empty' }),
  api_secret: z.string().optional(),
});

export const CredentialsFileSchema = z.object({
  env_profile: z
    .string()
    .regex(/^[a-z0-9-]+$/, {
      message: 'env_profile must be lowercase alphanumeric with hyphens',
    }),
  users: z.array(UserCredentialSchema).optional(),
  api_keys: z.array(ApiKeyCredentialSchema).optional(),
});

export type CredentialsFile = z.infer<typeof CredentialsFileSchema>;
export type UserCredential = z.infer<typeof UserCredentialSchema>;
export type ApiKeyCredential = z.infer<typeof ApiKeyCredentialSchema>;

/**
 * T008: TestReport Interface
 * Structured test report generated by e2e-runner
 */
export interface TestReportMetadata {
  env_profile: string;
  timestamp: string;
  duration: number;
  playwright_version?: string;
}

export interface TestReportStats {
  total: number;
  passed: number;
  failed: number;
  skipped: number;
  flaky?: number;
}

export interface TestReportArtifacts {
  html_report: string;
  json_results: string;
  traces_dir?: string;
  screenshots_dir?: string;
  videos_dir?: string;
}

export interface TestFailure {
  file: string;
  title: string;
  error: string;
  stack?: string;
  screenshot?: string;
  video?: string;
}

export interface TestReport {
  metadata: TestReportMetadata;
  stats: TestReportStats;
  artifacts: TestReportArtifacts;
  failures?: TestFailure[];
}
