package com.cinema.inventory.job;

import com.cinema.inventory.entity.InventoryReservation;
import com.cinema.inventory.entity.InventoryReservation.ReservationStatus;
import com.cinema.inventory.repository.InventoryReservationRepository;
import com.cinema.inventory.service.InventoryReservationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

/**
 * @spec O012-order-inventory-reservation
 * Inventory Reservation Cleanup Job
 *
 * Purpose: Automatically release expired inventory reservations
 * Runs every 5 minutes to release reservations older than 30 minutes
 *
 * Author: Generated by O012 spec
 * Date: 2026-01-14
 */
@Component
public class InventoryReservationCleanupJob {

    private static final Logger logger = LoggerFactory.getLogger(InventoryReservationCleanupJob.class);

    private final InventoryReservationRepository reservationRepository;
    private final InventoryReservationService reservationService;

    @Value("${inventory.reservation.expiry.minutes:30}")
    private int expiryMinutes;

    public InventoryReservationCleanupJob(
            InventoryReservationRepository reservationRepository,
            InventoryReservationService reservationService
    ) {
        this.reservationRepository = reservationRepository;
        this.reservationService = reservationService;
    }

    /**
     * Release expired inventory reservations
     * Runs every 5 minutes
     */
    @Scheduled(cron = "0 */5 * * * *")
    public void releaseExpiredReservations() {
        Instant expiryThreshold = Instant.now().minus(expiryMinutes, ChronoUnit.MINUTES);
        
        logger.info("Starting expired reservation cleanup job. Expiry threshold: {} minutes ago", expiryMinutes);

        List<InventoryReservation> expiredReservations = reservationRepository
                .findByStatusAndCreatedAtBefore(ReservationStatus.ACTIVE, expiryThreshold);

        if (expiredReservations.isEmpty()) {
            logger.info("No expired reservations found. Cleanup job completed.");
            return;
        }

        logger.info("Found {} expired reservations to release", expiredReservations.size());

        int successCount = 0;
        int failureCount = 0;

        for (InventoryReservation reservation : expiredReservations) {
            try {
                reservationService.releaseReservation(reservation.getOrderId());

                reservation.setStatus(ReservationStatus.EXPIRED);
                reservation.setNotes("超时自动释放 (Expired after " + expiryMinutes + " minutes)");
                reservationRepository.save(reservation);

                successCount++;
                logger.debug("Released expired reservation: orderId={}, skuId={}, quantity={}",
                        reservation.getOrderId(), 
                        reservation.getSkuId(), 
                        reservation.getReservedQuantity());

            } catch (Exception e) {
                failureCount++;
                logger.error("Failed to release expired reservation: orderId={}, reservationId={}, error={}",
                        reservation.getOrderId(), 
                        reservation.getId(), 
                        e.getMessage(), 
                        e);
            }
        }

        logger.info("Expired reservation cleanup completed. Total: {}, Success: {}, Failure: {}",
                expiredReservations.size(), successCount, failureCount);

        if (failureCount > 0 && (failureCount * 100.0 / expiredReservations.size()) > 10) {
            logger.error("High failure rate detected in reservation cleanup: {}% ({}/{})",
                    (failureCount * 100.0 / expiredReservations.size()),
                    failureCount,
                    expiredReservations.size());
        }
    }

    public String triggerManualCleanup() {
        logger.info("Manual cleanup triggered");
        releaseExpiredReservations();
        return "Manual cleanup completed. Check logs for details.";
    }
}
