/**
 * @spec P005-bom-inventory-deduction
 * BomSnapshot JPA Entity
 *
 * Purpose: Stores BOM formula snapshots at order creation time for version locking
 * Maps to: bom_snapshots table (created in V056)
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * BOM Snapshot Entity
 *
 * Stores BOM formula snapshots in JSONB format.
 * Ensures deduction uses the same formula even if BOM is modified after order placement.
 *
 * JSON structure example:
 * {
 *   "formulaId": "f001",
 *   "skuId": "sku-cocktail-001",
 *   "skuName": "威士忌可乐鸡尾酒",
 *   "components": [
 *     {
 *       "skuId": "raw001",
 *       "skuName": "威士忌",
 *       "quantity": 45,
 *       "unit": "ml",
 *       "wastageRate": 0.05
 *     }
 *   ]
 * }
 *
 * @see com.cinema.inventory.service.BomSnapshotService
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Entity
@Table(name = "bom_snapshots")
public class BomSnapshot {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "order_id", nullable = false)
    private UUID orderId;

    @Column(name = "finished_sku_id", nullable = false) // V054 table structure uses this column name
    private UUID skuId;

    @Column(name = "raw_material_sku_id", nullable = false) // V054 table structure
    private UUID rawMaterialSkuId;

    @Column(name = "quantity", nullable = false, precision = 15, scale = 4) // V054 table structure
    private BigDecimal quantity;

    @Column(name = "unit", nullable = false) // V054 table structure
    private String unit;

    @Column(name = "bom_level", nullable = false) // V054 table structure - BOM depth level
    private Integer bomLevel;

    // Note: V054 table structure doesn't have snapshot_data column, using individual columns instead
    // @JdbcTypeCode(SqlTypes.JSON)
    // @Column(name = "snapshot_data", nullable = false, columnDefinition = "jsonb")
    // private Map<String, Object> snapshotData;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
    }

    // Getters and Setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public UUID getRawMaterialSkuId() {
        return rawMaterialSkuId;
    }

    public void setRawMaterialSkuId(UUID rawMaterialSkuId) {
        this.rawMaterialSkuId = rawMaterialSkuId;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Integer getBomLevel() {
        return bomLevel;
    }

    public void setBomLevel(Integer bomLevel) {
        this.bomLevel = bomLevel;
    }

    // public Map<String, Object> getSnapshotData() {
    //     return snapshotData;
    // }

    // public void setSnapshotData(Map<String, Object> snapshotData) {
    //     this.snapshotData = snapshotData;
    // }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
