/**
 * @spec P005-bom-inventory-deduction
 * @spec I003-inventory-query
 * Inventory JPA Entity
 *
 * Purpose: JPA entity for store_inventory table with BOM reservation support
 * Maps to: store_inventory table (created in V033)
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 * Updated: 2026-01-11 - Added JPA relationships for inventory query
 */

package com.cinema.inventory.entity;

import com.cinema.hallstore.domain.Sku;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Inventory Entity
 *
 * Maps to store_inventory table.
 * Supports BOM-based inventory reservation and deduction.
 *
 * Key fields:
 * - onHandQty: Physical inventory quantity (现存库存)
 * - reservedQty: Locked for pending orders (预占库存)
 * - availableQty: Computed as onHandQty - reservedQty (可用库存)
 *
 * JPA Relationships:
 * - sku: Many-to-One with Sku entity (for name, code, mainUnit)
 * - store: Many-to-One with StoreEntity (for store name, code)
 *
 * @see com.cinema.inventory.service.InventoryReservationService
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Entity
@Table(name = "store_inventory")
public class Inventory {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "store_id", nullable = false, insertable = false, updatable = false)
    private UUID storeId;

    @Column(name = "sku_id", nullable = false, insertable = false, updatable = false)
    private UUID skuId;

    /**
     * 关联的 SKU 实体（用于查询时 JOIN FETCH）
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sku_id", nullable = false)
    private Sku sku;

    /**
     * 关联的门店实体（用于查询时 JOIN FETCH）
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "store_id", nullable = false)
    private StoreEntity store;

    /**
     * On-hand quantity (现存库存)
     * Physical inventory in the warehouse
     */
    @Column(name = "on_hand_qty", nullable = false, precision = 12, scale = 3)
    private BigDecimal onHandQty = BigDecimal.ZERO;

    /**
     * Available quantity (可用库存)
     * Computed as: onHandQty - reservedQty
     * Can be used for new orders
     */
    @Column(name = "available_qty", nullable = false, precision = 12, scale = 3)
    private BigDecimal availableQty = BigDecimal.ZERO;

    /**
     * Reserved quantity (预占库存)
     * Locked by pending orders, not yet deducted from on-hand
     */
    @Column(name = "reserved_qty", nullable = false, precision = 12, scale = 3)
    private BigDecimal reservedQty = BigDecimal.ZERO;

    /**
     * Safety stock threshold
     * Minimum quantity before triggering reorder alerts
     */
    @Column(name = "safety_stock", precision = 12, scale = 3)
    private BigDecimal safetyStock = BigDecimal.ZERO;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        updatedAt = Instant.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }

    // Getters and Setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public BigDecimal getOnHandQty() {
        return onHandQty;
    }

    public void setOnHandQty(BigDecimal onHandQty) {
        this.onHandQty = onHandQty;
    }

    public BigDecimal getAvailableQty() {
        return availableQty;
    }

    public void setAvailableQty(BigDecimal availableQty) {
        this.availableQty = availableQty;
    }

    public BigDecimal getReservedQty() {
        return reservedQty;
    }

    public void setReservedQty(BigDecimal reservedQty) {
        this.reservedQty = reservedQty;
    }

    public BigDecimal getSafetyStock() {
        return safetyStock;
    }

    public void setSafetyStock(BigDecimal safetyStock) {
        this.safetyStock = safetyStock;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Sku getSku() {
        return sku;
    }

    public void setSku(Sku sku) {
        this.sku = sku;
        if (sku != null) {
            this.skuId = sku.getId();
        }
    }

    public StoreEntity getStore() {
        return store;
    }

    public void setStore(StoreEntity store) {
        this.store = store;
        if (store != null) {
            this.storeId = store.getId();
        }
    }

    /**
     * Calculate truly available quantity for reservation
     * Formula: onHandQty - reservedQty
     *
     * @return Available quantity that can be reserved
     */
    public BigDecimal calculateAvailableForReservation() {
        return onHandQty.subtract(reservedQty);
    }

    /**
     * Check if sufficient inventory available for reservation
     *
     * @param quantity Quantity to reserve
     * @return true if sufficient, false otherwise
     */
    public boolean hasSufficientAvailable(BigDecimal quantity) {
        return calculateAvailableForReservation().compareTo(quantity) >= 0;
    }
}
