/**
 * @spec P005-bom-inventory-deduction
 * InventoryTransaction JPA Entity
 *
 * Purpose: Tracks all inventory transactions for audit trail
 * Maps to: inventory_transactions table (extended in V057)
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Inventory Transaction Entity
 *
 * Comprehensive audit log for all inventory changes.
 * Supports multiple transaction types including BOM deduction.
 *
 * Transaction types:
 * - BOM_RESERVATION: Inventory reserved for order (informational)
 * - BOM_DEDUCTION: Actual inventory consumption
 * - RESERVATION_RELEASE: Reservation cancelled/expired
 * - ADJUSTMENT_SURPLUS: Manual adjustment (increase)
 * - ADJUSTMENT_SHORTAGE: Manual adjustment (decrease)
 * - DAMAGE: Damaged goods
 * - TRANSFER_IN/OUT: Inter-store transfers
 *
 * @see com.cinema.inventory.service.InventoryDeductionService
 */
@Entity
@Table(name = "inventory_transactions")
public class InventoryTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "store_id", nullable = false)
    private UUID storeId;

    @Column(name = "sku_id", nullable = false)
    private UUID skuId;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 50)
    private TransactionType transactionType;

    /**
     * Quantity change
     * Positive = increase (e.g., adjustment surplus, transfer in)
     * Negative = decrease (e.g., deduction, damage)
     * Zero = informational (e.g., reservation events)
     */
    @Column(name = "quantity", nullable = false)
    private BigDecimal quantity;

    @Column(name = "stock_before", nullable = false)
    private BigDecimal quantityBefore;

    @Column(name = "stock_after", nullable = false)
    private BigDecimal quantityAfter;

    /**
     * Related order ID (for BOM transactions)
     * Links transaction to the order that triggered it
     */
    @Column(name = "related_order_id")
    private UUID relatedOrderId;

    /**
     * BOM snapshot ID (for audit trail)
     * References the BOM formula version used for deduction
     */
    @Column(name = "bom_snapshot_id")
    private UUID bomSnapshotId;

    @Column(name = "adjustment_reason_id", insertable = false, updatable = false)
    private UUID adjustmentReasonId;

    @Column(name = "operator_id", nullable = false)
    private UUID operatorId;

    @Column(name = "transaction_time", nullable = false)
    private Instant operatedAt;

    @Column(name = "remarks")
    private String notes;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        if (operatedAt == null) {
            operatedAt = Instant.now();
        }
    }

    // Getters and Setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public TransactionType getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getQuantityBefore() {
        return quantityBefore;
    }

    public void setQuantityBefore(BigDecimal quantityBefore) {
        this.quantityBefore = quantityBefore;
    }

    public BigDecimal getQuantityAfter() {
        return quantityAfter;
    }

    public void setQuantityAfter(BigDecimal quantityAfter) {
        this.quantityAfter = quantityAfter;
    }

    public UUID getRelatedOrderId() {
        return relatedOrderId;
    }

    public void setRelatedOrderId(UUID relatedOrderId) {
        this.relatedOrderId = relatedOrderId;
    }

    public UUID getBomSnapshotId() {
        return bomSnapshotId;
    }

    public void setBomSnapshotId(UUID bomSnapshotId) {
        this.bomSnapshotId = bomSnapshotId;
    }

    public UUID getAdjustmentReasonId() {
        return adjustmentReasonId;
    }

    public void setAdjustmentReasonId(UUID adjustmentReasonId) {
        this.adjustmentReasonId = adjustmentReasonId;
    }

    public UUID getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(UUID operatorId) {
        this.operatorId = operatorId;
    }

    public Instant getOperatedAt() {
        return operatedAt;
    }

    public void setOperatedAt(Instant operatedAt) {
        this.operatedAt = operatedAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Transaction Type Enum
     * Note: Enum names MUST match database check constraint values (lowercase with underscores)
     * Database allows: purchase_in, sale_out, adjustment_in, adjustment_out, damage_out,
     *                  transfer_in, transfer_out, return_in, return_out, safety_stock_update
     */
    public enum TransactionType {
        purchase_in,
        sale_out,
        adjustment_in,
        adjustment_out,
        damage_out,
        transfer_in,
        transfer_out,
        return_in,
        return_out,
        safety_stock_update
    }
}
