/**
 * @spec P005-bom-inventory-deduction
 * InventoryReservation JPA Entity
 *
 * Purpose: Tracks inventory reservations created when orders are placed
 * Maps to: inventory_reservations table (created in V055)
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Inventory Reservation Entity
 *
 * Records inventory locks created during order placement.
 * Prevents overselling by tracking reserved quantities.
 *
 * State machine:
 * ACTIVE → FULFILLED (on order fulfillment)
 * ACTIVE → CANCELLED (on order cancellation)
 * ACTIVE → EXPIRED (on timeout)
 *
 * @see com.cinema.inventory.service.InventoryReservationService
 */
@Entity
@Table(name = "inventory_reservations")
public class InventoryReservation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "order_id", nullable = false)
    private UUID orderId;

    @Column(name = "store_id", nullable = false)
    private UUID storeId;

    @Column(name = "sku_id", nullable = false)
    private UUID skuId;

    @Column(name = "quantity", nullable = false, precision = 15, scale = 4)
    private BigDecimal quantity;

    @Column(name = "reserved_quantity", nullable = false, precision = 15, scale = 4)
    private BigDecimal reservedQuantity;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ReservationStatus status = ReservationStatus.ACTIVE;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "fulfilled_at")
    private Instant fulfilledAt;

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Column(name = "notes")
    private String notes;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
    }

    /**
     * Mark reservation as fulfilled
     */
    public void markAsFulfilled() {
        this.status = ReservationStatus.FULFILLED;
        this.fulfilledAt = Instant.now();
    }

    /**
     * Mark reservation as cancelled
     */
    public void markAsCancelled() {
        this.status = ReservationStatus.CANCELLED;
        this.cancelledAt = Instant.now();
    }

    /**
     * Mark reservation as expired
     */
    public void markAsExpired() {
        this.status = ReservationStatus.EXPIRED;
        this.cancelledAt = Instant.now();
    }

    /**
     * Check if reservation is active
     */
    public boolean isActive() {
        return status == ReservationStatus.ACTIVE;
    }

    // Getters and Setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getReservedQuantity() {
        return reservedQuantity;
    }

    public void setReservedQuantity(BigDecimal reservedQuantity) {
        this.reservedQuantity = reservedQuantity;
    }

    public ReservationStatus getStatus() {
        return status;
    }

    public void setStatus(ReservationStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public Instant getFulfilledAt() {
        return fulfilledAt;
    }

    public void setFulfilledAt(Instant fulfilledAt) {
        this.fulfilledAt = fulfilledAt;
    }

    public Instant getCancelledAt() {
        return cancelledAt;
    }

    public void setCancelledAt(Instant cancelledAt) {
        this.cancelledAt = cancelledAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * Reservation Status Enum
     */
    public enum ReservationStatus {
        /**
         * Active reservation, inventory is locked
         */
        ACTIVE,

        /**
         * Reservation fulfilled, inventory deducted
         */
        FULFILLED,

        /**
         * Reservation cancelled, inventory released
         */
        CANCELLED,

        /**
         * Reservation expired, inventory released
         */
        EXPIRED
    }
}
