openapi: 3.0.3
info:
  title: 供应商编辑 API
  description: |
    @spec N003-supplier-edit
    供应商创建和更新接口定义
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 本地开发服务器

paths:
  /api/suppliers:
    post:
      summary: 创建供应商
      description: 新建一个供应商记录
      operationId: createSupplier
      tags:
        - Supplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierCreateRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: 'SUP_VAL_001'
                message: '供应商名称不能为空'
                timestamp: '2026-01-11T10:00:00Z'
        '409':
          description: 供应商编码已存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: 'SUP_DUP_001'
                message: '供应商编码已存在'
                details:
                  code: 'S001'
                timestamp: '2026-01-11T10:00:00Z'

  /api/suppliers/{id}:
    put:
      summary: 更新供应商
      description: 更新指定供应商的信息（编码不可修改）
      operationId: updateSupplier
      tags:
        - Supplier
      parameters:
        - name: id
          in: path
          required: true
          description: 供应商 ID (UUID)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierUpdateRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 供应商不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: 'SUP_NTF_001'
                message: '供应商不存在'
                details:
                  id: '550e8400-e29b-41d4-a716-446655440000'
                timestamp: '2026-01-11T10:00:00Z'

components:
  schemas:
    SupplierCreateRequest:
      type: object
      required:
        - code
        - name
        - status
      properties:
        code:
          type: string
          maxLength: 50
          description: 供应商编码
          example: 'S001'
        name:
          type: string
          maxLength: 200
          description: 供应商名称
          example: '华润万家'
        contactName:
          type: string
          maxLength: 100
          nullable: true
          description: 联系人姓名
          example: '张三'
        contactPhone:
          type: string
          pattern: '^1[3-9]\d{9}$'
          nullable: true
          description: 联系电话（中国大陆手机号）
          example: '13800138000'
        status:
          $ref: '#/components/schemas/SupplierStatus'

    SupplierUpdateRequest:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
          maxLength: 200
          description: 供应商名称
          example: '华润万家'
        contactName:
          type: string
          maxLength: 100
          nullable: true
          description: 联系人姓名
          example: '李四'
        contactPhone:
          type: string
          pattern: '^1[3-9]\d{9}$'
          nullable: true
          description: 联系电话（中国大陆手机号）
          example: '13900139000'
        status:
          $ref: '#/components/schemas/SupplierStatus'

    SupplierDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 供应商 ID
        code:
          type: string
          description: 供应商编码
        name:
          type: string
          description: 供应商名称
        contactName:
          type: string
          nullable: true
          description: 联系人姓名
        contactPhone:
          type: string
          nullable: true
          description: 联系电话
        status:
          $ref: '#/components/schemas/SupplierStatus'

    SupplierStatus:
      type: string
      enum:
        - ACTIVE
        - SUSPENDED
        - TERMINATED
      description: |
        供应商状态:
        - ACTIVE: 启用
        - SUSPENDED: 暂停
        - TERMINATED: 终止

    SupplierResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/SupplierDTO'
        timestamp:
          type: string
          format: date-time
          example: '2026-01-11T10:00:00Z'
        message:
          type: string
          example: '操作成功'

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: 错误编号
          example: 'SUP_VAL_001'
        message:
          type: string
          description: 错误消息
          example: '供应商名称不能为空'
        details:
          type: object
          additionalProperties: true
          description: 错误详情
        timestamp:
          type: string
          format: date-time
          example: '2026-01-11T10:00:00Z'

tags:
  - name: Supplier
    description: 供应商管理接口
