openapi: 3.0.3
info:
  title: N004 Procurement Material Selector API
  description: |
    API contracts for N004-procurement-material-selector feature.
    Supports Material and SKU procurement with automatic unit conversion.
  version: 1.0.0
  contact:
    name: Cinema Business Platform Team

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: Materials
    description: Material selector endpoints
  - name: Procurement Orders
    description: Procurement order management with Material/SKU support

paths:
  /materials:
    get:
      tags:
        - Materials
      summary: Get material list for selector
      description: |
        Fetch materials for <MaterialSkuSelector /> component.
        Supports filtering by category and fuzzy search.
      parameters:
        - name: category
          in: query
          description: Filter by material category
          required: false
          schema:
            type: string
            enum: [RAW_MATERIAL, PACKAGING, SEMI_FINISHED]
        - name: search
          in: query
          description: Fuzzy search on name, code, or specification
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number (0-indexed)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Material list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MaterialDTO'
                  total:
                    type: integer
                    description: Total count of materials
                    example: 150
                  page:
                    type: integer
                    example: 0
                  pageSize:
                    type: integer
                    example: 20
                  timestamp:
                    type: string
                    format: date-time
                    example: '2026-01-11T10:00:00Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /procurement/orders:
    post:
      tags:
        - Procurement Orders
      summary: Create procurement order (supports Material and SKU)
      description: |
        Create a new procurement order with Material or SKU items.
        System validates item type and auto-fills unit from Material/SKU entity.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePurchaseOrderRequest'
      responses:
        '201':
          description: Purchase order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/PurchaseOrderDTO'
                  timestamp:
                    type: string
                    format: date-time
                    example: '2026-01-11T10:00:00Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /procurement/orders/{orderId}:
    get:
      tags:
        - Procurement Orders
      summary: Get purchase order details
      description: |
        Retrieve purchase order with items (supports both Material and SKU types).
        Response includes converted inventory quantity for Material items.
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Purchase order retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/PurchaseOrderDTO'
                  timestamp:
                    type: string
                    format: date-time
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /procurement/orders/{orderId}/inbound:
    post:
      tags:
        - Procurement Orders
      summary: Execute procurement inbound with unit conversion
      description: |
        Execute inbound operation for procurement order.
        For Material items, system auto-converts purchaseUnit to inventoryUnit
        using M001's CommonConversionService.
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Inbound operation completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      orderId:
                        type: string
                        format: uuid
                      inboundItems:
                        type: array
                        items:
                          type: object
                          properties:
                            itemId:
                              type: string
                              format: uuid
                            itemType:
                              type: string
                              enum: [MATERIAL, SKU]
                            purchaseQuantity:
                              type: number
                              description: Quantity in purchase unit
                              example: 10
                            purchaseUnit:
                              type: string
                              example: '瓶'
                            inventoryQuantity:
                              type: number
                              description: Converted quantity in inventory unit
                              example: 5000
                            inventoryUnit:
                              type: string
                              example: 'ml'
                  timestamp:
                    type: string
                    format: date-time
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    MaterialDTO:
      type: object
      description: Material entity from M001
      required:
        - id
        - code
        - name
        - category
        - purchaseUnitId
        - inventoryUnitId
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          example: 'MAT-RAW-001'
          maxLength: 50
        name:
          type: string
          example: '可乐糖浆'
          maxLength: 200
        category:
          type: string
          enum: [RAW_MATERIAL, PACKAGING, SEMI_FINISHED]
          example: RAW_MATERIAL
        specification:
          type: string
          nullable: true
          example: '5L装'
          maxLength: 500
        purchaseUnitId:
          type: string
          format: uuid
        inventoryUnitId:
          type: string
          format: uuid
        conversionRate:
          type: number
          format: decimal
          description: Material-level conversion rate (purchase to inventory)
          example: 500.0
        useGlobalConversion:
          type: boolean
          description: Whether to use global conversion rules
          example: false
        purchaseUnit:
          $ref: '#/components/schemas/UnitDTO'
        inventoryUnit:
          $ref: '#/components/schemas/UnitDTO'

    UnitDTO:
      type: object
      description: Unit entity (joined from M001)
      required:
        - id
        - code
        - name
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          example: 'BOTTLE'
          maxLength: 20
        name:
          type: string
          example: '瓶'
          maxLength: 50

    CreatePurchaseOrderRequest:
      type: object
      required:
        - supplierId
        - items
      properties:
        supplierId:
          type: string
          format: uuid
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CreatePurchaseOrderItemRequest'

    CreatePurchaseOrderItemRequest:
      type: object
      required:
        - itemType
        - quantity
        - unitPrice
      properties:
        itemType:
          type: string
          enum: [MATERIAL, SKU]
          description: |
            Item type:
            - MATERIAL: Use materialId, system auto-fills unit from material.purchaseUnit
            - SKU: Use skuId, system auto-fills unit from sku.mainUnit
        materialId:
          type: string
          format: uuid
          description: Required if itemType = MATERIAL, must be null if itemType = SKU
        skuId:
          type: string
          format: uuid
          description: Required if itemType = SKU, must be null if itemType = MATERIAL
        quantity:
          type: number
          format: decimal
          minimum: 0.001
          description: Procurement quantity (in purchase unit)
          example: 10
        unitPrice:
          type: number
          format: decimal
          minimum: 0.01
          description: Unit price
          example: 50.00

    PurchaseOrderDTO:
      type: object
      required:
        - id
        - orderNo
        - supplierId
        - status
        - items
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        orderNo:
          type: string
          example: 'PO-2026-001'
        supplierId:
          type: string
          format: uuid
        status:
          type: string
          enum: [DRAFT, SUBMITTED, APPROVED, IN_TRANSIT, RECEIVED, CANCELLED]
          example: DRAFT
        items:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseOrderItemDTO'
        totalAmount:
          type: number
          format: decimal
          description: Total order amount
          example: 1250.00
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PurchaseOrderItemDTO:
      type: object
      required:
        - id
        - itemType
        - quantity
        - unit
        - unitPrice
        - totalPrice
      properties:
        id:
          type: string
          format: uuid
        itemType:
          type: string
          enum: [MATERIAL, SKU]
        materialId:
          type: string
          format: uuid
          nullable: true
          description: Populated if itemType = MATERIAL
        materialName:
          type: string
          nullable: true
          description: Material name (redundancy for soft-delete scenarios)
          example: '可乐糖浆'
        material:
          $ref: '#/components/schemas/MaterialDTO'
          nullable: true
          description: Populated if itemType = MATERIAL
        skuId:
          type: string
          format: uuid
          nullable: true
          description: Populated if itemType = SKU
        sku:
          $ref: '#/components/schemas/SkuDTO'
          nullable: true
          description: Populated if itemType = SKU
        quantity:
          type: number
          format: decimal
          example: 10
        unit:
          type: string
          description: Purchase unit (from Material.purchaseUnit or SKU.mainUnit)
          example: '瓶'
        unitPrice:
          type: number
          format: decimal
          example: 50.00
        totalPrice:
          type: number
          format: decimal
          description: quantity * unitPrice
          example: 500.00
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    SkuDTO:
      type: object
      description: SKU entity (minimal fields for N004)
      required:
        - id
        - code
        - name
        - mainUnit
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          example: 'SKU-DRINK-001'
        name:
          type: string
          example: '可口可乐中杯'
        mainUnit:
          type: string
          example: '杯'
        specification:
          type: string
          nullable: true
          example: '500ml'

    ErrorResponse:
      type: object
      required:
        - success
        - error
        - message
        - timestamp
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error code (e.g., PROC_VAL_001)
          example: 'PROC_VAL_001'
        message:
          type: string
          description: Human-readable error message
          example: 'Item type and ID mismatch: MATERIAL items must have materialId'
        details:
          type: object
          nullable: true
          description: Additional error context
        timestamp:
          type: string
          format: date-time
          example: '2026-01-11T10:00:00Z'

  responses:
    BadRequest:
      description: Validation error or malformed request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            itemTypeMismatch:
              summary: Item type and ID mismatch
              value:
                success: false
                error: 'PROC_VAL_001'
                message: 'Item type and ID mismatch: MATERIAL items must have materialId, SKU items must have skuId'
                details:
                  itemType: 'MATERIAL'
                  materialId: null
                  skuId: 'uuid-123'
                timestamp: '2026-01-11T10:00:00Z'
            missingUnitConfig:
              summary: Material missing unit configuration
              value:
                success: false
                error: 'PROC_VAL_002'
                message: '该物料尚未配置采购单位或库存单位，无法采购'
                details:
                  materialId: 'uuid-456'
                  code: 'MAT-RAW-001'
                  purchaseUnitId: null
                timestamp: '2026-01-11T10:00:00Z'
            conversionFailed:
              summary: Unit conversion failed
              value:
                success: false
                error: 'PROC_CONV_001'
                message: '单位换算失败：kg 无法换算为 ml，请检查物料配置'
                details:
                  materialId: 'uuid-789'
                  fromUnit: 'kg'
                  toUnit: 'ml'
                timestamp: '2026-01-11T10:00:00Z'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: 'PROC_NTF_001'
            message: 'Purchase order not found'
            details:
              orderId: 'uuid-999'
            timestamp: '2026-01-11T10:00:00Z'

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: 'PROC_SYS_001'
            message: 'Internal server error'
            details: null
            timestamp: '2026-01-11T10:00:00Z'
