/**
 * @spec P005-bom-inventory-deduction
 * C端库存服务 - Taro 库存API客户端
 *
 * Purpose: Provides inventory reservation and deduction API clients for C端 order flow
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

import Taro from '@tarojs/taro';

const API_BASE = process.env.TARO_APP_API || 'http://localhost:8080/api';

/**
 * Get authorization token from storage
 */
function getToken(): string {
  return Taro.getStorageSync('token') || '';
}

/**
 * Request options interface
 */
interface RequestOptions {
  url: string;
  method: 'GET' | 'POST' | 'DELETE' | 'PUT';
  data?: any;
  header?: Record<string, string>;
}

/**
 * Generic request wrapper with authentication
 */
async function request<T>(options: RequestOptions): Promise<T> {
  const response = await Taro.request({
    ...options,
    header: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${getToken()}`,
      ...options.header
    }
  });

  if (response.statusCode >= 400) {
    throw response.data;
  }

  return response.data as T;
}

/**
 * API Response interfaces
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  details?: any;
  timestamp: string;
}

export interface ReservationRequest {
  orderId: string;
  storeId: string;
  items: Array<{
    skuId: string;
    quantity: number;
    unit: string;
  }>;
}

export interface ReservationResponse {
  orderId: string;
  reservationIds: string[];
  reservedComponents: Array<{
    skuId: string;
    skuName: string;
    quantity: number;
    unit: string;
  }>;
}

export interface DeductionRequest {
  orderId: string;
  storeId: string;
}

export interface DeductionResponse {
  orderId: string;
  deductedComponents: Array<{
    skuId: string;
    skuName: string;
    quantity: number;
    unit: string;
  }>;
}

/**
 * Inventory Service API
 */
export const inventoryService = {
  /**
   * Reserve inventory for order (预占库存)
   * Called before order creation to lock inventory
   */
  reserveInventory: async (
    request: ReservationRequest
  ): Promise<ApiResponse<ReservationResponse>> => {
    return request<ApiResponse<ReservationResponse>>({
      url: `${API_BASE}/inventory/reservations`,
      method: 'POST',
      data: request
    });
  },

  /**
   * Deduct inventory on fulfillment (实扣库存)
   * Called when order is confirmed/fulfilled
   */
  deductInventory: async (
    request: DeductionRequest
  ): Promise<ApiResponse<DeductionResponse>> => {
    return request<ApiResponse<DeductionResponse>>({
      url: `${API_BASE}/inventory/deductions`,
      method: 'POST',
      data: request
    });
  },

  /**
   * Release reservation on order cancellation (释放预占)
   */
  releaseReservation: async (orderId: string): Promise<ApiResponse<void>> => {
    return request<ApiResponse<void>>({
      url: `${API_BASE}/inventory/reservations/${orderId}`,
      method: 'DELETE'
    });
  }
};
