/**
 * @spec P005-bom-inventory-deduction
 * BomDepthExceededException
 *
 * Purpose: Exception thrown when BOM expansion exceeds maximum allowed depth
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.exception;

import java.util.Map;
import java.util.UUID;

/**
 * BOM Depth Exceeded Exception
 *
 * Thrown when attempting to expand BOM beyond MAX_DEPTH (3 levels).
 * This prevents:
 * - Infinite recursion
 * - Overly complex product structures
 * - Performance degradation
 *
 * Error code: INV_BIZ_004
 */
public class BomDepthExceededException extends BusinessException {

    private final UUID skuId;
    private final int currentDepth;
    private final int maxDepth;

    public BomDepthExceededException(UUID skuId, int currentDepth, int maxDepth) {
        super(
                InventoryErrorCode.INV_BIZ_004,
                String.format(
                        "BOM expansion depth (%d) exceeded maximum allowed depth (%d) for SKU: %s",
                        currentDepth, maxDepth, skuId
                ),
                Map.of(
                        "skuId", skuId,
                        "currentDepth", currentDepth,
                        "maxDepth", maxDepth
                )
        );
        this.skuId = skuId;
        this.currentDepth = currentDepth;
        this.maxDepth = maxDepth;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public int getCurrentDepth() {
        return currentDepth;
    }

    public int getMaxDepth() {
        return maxDepth;
    }
}
