/**
 * @spec P005-bom-inventory-deduction
 * Business Exception Base Class
 *
 * Purpose: Base class for all inventory business exceptions
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.exception;

import java.util.Collections;
import java.util.Map;

/**
 * Business Exception
 *
 * Base class for inventory business rule violations.
 * Carries error code and optional details.
 */
public class BusinessException extends RuntimeException {

    private final InventoryErrorCode errorCode;
    private final Map<String, Object> details;

    public BusinessException(InventoryErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.details = Collections.emptyMap();
    }

    public BusinessException(InventoryErrorCode errorCode, Map<String, Object> details) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.details = details != null ? details : Collections.emptyMap();
    }

    public BusinessException(InventoryErrorCode errorCode, String customMessage) {
        super(customMessage);
        this.errorCode = errorCode;
        this.details = Collections.emptyMap();
    }

    public BusinessException(InventoryErrorCode errorCode, String customMessage, Map<String, Object> details) {
        super(customMessage);
        this.errorCode = errorCode;
        this.details = details != null ? details : Collections.emptyMap();
    }

    public InventoryErrorCode getErrorCode() {
        return errorCode;
    }

    public Map<String, Object> getDetails() {
        return details;
    }
}
