/**
 * @spec P005-bom-inventory-deduction
 * InsufficientInventoryException
 *
 * Purpose: Exception thrown when inventory is insufficient for reservation
 * Error Code: INV_BIZ_001
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.exception;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Insufficient Inventory Exception
 *
 * Thrown when available inventory is less than required quantity.
 * Provides detailed shortage information for user feedback.
 */
public class InsufficientInventoryException extends BusinessException {

    private final List<InventoryShortage> shortages;

    public InsufficientInventoryException(List<InventoryShortage> shortages) {
        super(
                InventoryErrorCode.INV_BIZ_001,
                "Insufficient inventory for order",
                Map.of("shortages", shortages)
        );
        this.shortages = shortages;
    }

    public InsufficientInventoryException(InventoryShortage shortage) {
        this(List.of(shortage));
    }

    public List<InventoryShortage> getShortages() {
        return shortages;
    }

    @Override
    public Map<String, Object> getDetails() {
        return Map.of(
                "shortages", shortages.stream()
                        .map(s -> Map.of(
                                "skuId", s.skuId().toString(),
                                "skuName", s.skuName(),
                                "available", s.available(),
                                "required", s.required(),
                                "shortage", s.shortage(),
                                "unit", s.unit()
                        ))
                        .collect(Collectors.toList())
        );
    }

    /**
     * Inventory Shortage Details
     *
     * @param skuId SKU ID of the shortage item
     * @param skuName SKU name for display
     * @param available Available quantity
     * @param required Required quantity
     * @param shortage Shortage amount (required - available)
     * @param unit Unit of measurement
     */
    public record InventoryShortage(
            UUID skuId,
            String skuName,
            BigDecimal available,
            BigDecimal required,
            BigDecimal shortage,
            String unit
    ) {
        public InventoryShortage {
            if (shortage == null) {
                shortage = required.subtract(available);
            }
        }
    }
}
