/**
 * @spec P005-bom-inventory-deduction
 * InsufficientCurrentInventoryException
 *
 * Purpose: Exception for when current inventory is less than reserved inventory during deduction
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.exception;

import java.util.Map;

/**
 * Insufficient Current Inventory Exception
 *
 * Thrown when attempting to deduct inventory but current_quantity < reserved_quantity,
 * indicating a data inconsistency that requires admin attention.
 *
 * This is a critical error scenario (INV_BIZ_002) that should trigger:
 * 1. Transaction rollback
 * 2. Admin notification
 * 3. Detailed error logging
 */
public class InsufficientCurrentInventoryException extends BusinessException {

    private final String skuName;
    private final java.math.BigDecimal currentQuantity;
    private final java.math.BigDecimal reservedQuantity;

    public InsufficientCurrentInventoryException(
            String skuName,
            java.math.BigDecimal currentQuantity,
            java.math.BigDecimal reservedQuantity
    ) {
        super(
                InventoryErrorCode.INV_BIZ_002,
                String.format(
                        "Current inventory (%s) is less than reserved inventory (%s) for SKU: %s",
                        currentQuantity, reservedQuantity, skuName
                ),
                Map.of(
                        "skuName", skuName,
                        "currentQuantity", currentQuantity,
                        "reservedQuantity", reservedQuantity,
                        "shortage", reservedQuantity.subtract(currentQuantity)
                )
        );
        this.skuName = skuName;
        this.currentQuantity = currentQuantity;
        this.reservedQuantity = reservedQuantity;
    }

    public String getSkuName() {
        return skuName;
    }

    public java.math.BigDecimal getCurrentQuantity() {
        return currentQuantity;
    }

    public java.math.BigDecimal getReservedQuantity() {
        return reservedQuantity;
    }
}
