/**
 * @spec P005-bom-inventory-deduction
 * Inventory Error Code Enumeration
 *
 * Purpose: Standardized error codes for inventory operations
 * Format: <MODULE>_<CATEGORY>_<NUMBER>
 *   - MODULE: INV (Inventory)
 *   - CATEGORY: VAL (Validation), NTF (Not Found), DUP (Duplicate), BIZ (Business Rule), SYS (System Error)
 *   - NUMBER: 3-digit sequence (001-999)
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 *
 * @see specs/P005-bom-inventory-deduction/contracts/error-codes.md
 */

package com.cinema.inventory.exception;

import org.springframework.http.HttpStatus;

/**
 * Inventory Error Codes
 *
 * All error codes follow the format: INV_<CATEGORY>_<NUMBER>
 */
public enum InventoryErrorCode {

    // ========== Validation Errors (VAL) - HTTP 400 ==========
    INV_VAL_001("Invalid reservation request", HttpStatus.BAD_REQUEST),
    INV_VAL_002("Invalid SKU ID format", HttpStatus.BAD_REQUEST),
    INV_VAL_003("Invalid quantity", HttpStatus.BAD_REQUEST),
    INV_VAL_004("Missing required field: %s", HttpStatus.BAD_REQUEST),
    INV_VAL_005("Invalid deduction request", HttpStatus.BAD_REQUEST),
    INV_VAL_006("Invalid manual adjustment", HttpStatus.BAD_REQUEST),

    // ========== Not Found Errors (NTF) - HTTP 404 ==========
    INV_NTF_001("No active reservations found for order", HttpStatus.NOT_FOUND),
    INV_NTF_002("Inventory record not found", HttpStatus.NOT_FOUND),
    INV_NTF_003("BOM formula not found", HttpStatus.NOT_FOUND),
    INV_NTF_004("Order not found", HttpStatus.NOT_FOUND),
    INV_NTF_005("Transaction log not found", HttpStatus.NOT_FOUND),

    // ========== Conflict Errors (DUP) - HTTP 409 ==========
    INV_DUP_001("Reservation already exists for order", HttpStatus.CONFLICT),
    INV_DUP_002("Order already fulfilled", HttpStatus.CONFLICT),

    // ========== Business Rule Errors (BIZ) - HTTP 422 ==========
    INV_BIZ_001("Insufficient inventory for order", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_002("Insufficient current inventory for deduction", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_003("Reservation has expired", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_004("BOM depth exceeds maximum (3 layers)", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_005("Circular BOM dependency detected", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_006("Cannot release non-active reservation", HttpStatus.UNPROCESSABLE_ENTITY),
    INV_BIZ_007("Inventory negative after deduction", HttpStatus.UNPROCESSABLE_ENTITY),

    // ========== System Errors (SYS) - HTTP 500 ==========
    INV_SYS_001("Internal server error during reservation", HttpStatus.INTERNAL_SERVER_ERROR),
    INV_SYS_002("Internal server error during deduction", HttpStatus.INTERNAL_SERVER_ERROR),
    INV_SYS_003("Database transaction rollback", HttpStatus.INTERNAL_SERVER_ERROR),
    INV_SYS_004("Lock acquisition timeout", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String message;
    private final HttpStatus httpStatus;

    InventoryErrorCode(String message, HttpStatus httpStatus) {
        this.message = message;
        this.httpStatus = httpStatus;
    }

    /**
     * Get error code (enum name)
     * @return Error code string (e.g., "INV_BIZ_001")
     */
    public String getCode() {
        return this.name();
    }

    /**
     * Get error message
     * @return Human-readable error message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Get HTTP status code
     * @return HTTP status for this error type
     */
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    /**
     * Format message with parameters
     * @param args Message parameters for String.format
     * @return Formatted message
     */
    public String formatMessage(Object... args) {
        return String.format(this.message, args);
    }
}
