/**
 * @spec P005-bom-inventory-deduction
 * Global Exception Handler
 *
 * Purpose: Centralized exception handling for inventory operations
 * Converts exceptions to standardized API error responses
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.exception;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

/**
 * Global Exception Handler
 *
 * Catches exceptions from inventory controllers and converts them to
 * standardized API responses following the format:
 * {
 *   "success": false,
 *   "error": "ERROR_CODE",
 *   "message": "Human-readable message",
 *   "details": { ... },
 *   "timestamp": "ISO-8601 timestamp"
 * }
 *
 * @see InventoryErrorCode
 */
@RestControllerAdvice(basePackages = "com.cinema.inventory")
public class InventoryGlobalExceptionHandler {

    private static final Logger logger = LoggerFactory.getLogger(InventoryGlobalExceptionHandler.class);

    /**
     * Handle validation errors (e.g., @Valid annotation)
     * Maps to INV_VAL_* error codes
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handleValidationException(MethodArgumentNotValidException ex) {
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getFieldErrors().forEach(error ->
                errors.put(error.getField(), error.getDefaultMessage())
        );

        ErrorResponse response = new ErrorResponse(
                false,
                InventoryErrorCode.INV_VAL_001.getCode(),
                "Validation failed",
                Map.of("fieldErrors", errors),
                Instant.now().toString()
        );

        logger.warn("Validation error: {}", errors);
        return ResponseEntity
                .status(InventoryErrorCode.INV_VAL_001.getHttpStatus())
                .body(response);
    }

    /**
     * Handle business exception (generic)
     * Uses error code from exception
     */
    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<ErrorResponse> handleBusinessException(BusinessException ex) {
        InventoryErrorCode errorCode = ex.getErrorCode();

        ErrorResponse response = new ErrorResponse(
                false,
                errorCode.getCode(),
                errorCode.getMessage(),
                ex.getDetails(),
                Instant.now().toString()
        );

        logger.warn("Business exception: {} - {}", errorCode.getCode(), errorCode.getMessage());
        return ResponseEntity
                .status(errorCode.getHttpStatus())
                .body(response);
    }

    /**
     * Handle generic runtime exceptions
     * Maps to INV_SYS_001 (internal server error)
     */
    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<ErrorResponse> handleRuntimeException(RuntimeException ex) {
        InventoryErrorCode errorCode = InventoryErrorCode.INV_SYS_001;

        ErrorResponse response = new ErrorResponse(
                false,
                errorCode.getCode(),
                errorCode.getMessage(),
                Map.of("exceptionMessage", ex.getMessage()),
                Instant.now().toString()
        );

        logger.error("Runtime exception", ex);
        return ResponseEntity
                .status(errorCode.getHttpStatus())
                .body(response);
    }

    /**
     * Handle all other exceptions
     * Fallback handler
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleGenericException(Exception ex) {
        InventoryErrorCode errorCode = InventoryErrorCode.INV_SYS_001;

        ErrorResponse response = new ErrorResponse(
                false,
                errorCode.getCode(),
                "An unexpected error occurred",
                Map.of("exceptionType", ex.getClass().getSimpleName()),
                Instant.now().toString()
        );

        logger.error("Unexpected exception", ex);
        return ResponseEntity
                .status(errorCode.getHttpStatus())
                .body(response);
    }

    /**
     * Error Response DTO
     */
    public record ErrorResponse(
            boolean success,
            String error,
            String message,
            Map<String, Object> details,
            String timestamp
    ) {
    }
}
