/**
 * @spec P005-bom-inventory-deduction
 * Migration: Create inventory_reservations table
 *
 * Purpose: Track inventory reservation locks created when orders are placed
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

-- Create inventory_reservations table
CREATE TABLE IF NOT EXISTS inventory_reservations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    sku_id UUID NOT NULL REFERENCES skus(id) ON DELETE CASCADE,
    reserved_quantity DECIMAL(15, 4) NOT NULL CHECK (reserved_quantity > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ, -- Optional: auto-release after timeout (e.g., 30 minutes)
    fulfilled_at TIMESTAMPTZ, -- When order was fulfilled and inventory deducted
    cancelled_at TIMESTAMPTZ, -- When reservation was released due to order cancellation
    notes TEXT,
    CONSTRAINT chk_reservation_status CHECK (status IN ('ACTIVE', 'FULFILLED', 'CANCELLED', 'EXPIRED'))
);

-- Add missing columns if table already exists (from V054)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_reservations' AND column_name = 'reserved_quantity'
    ) THEN
        ALTER TABLE inventory_reservations ADD COLUMN reserved_quantity DECIMAL(15, 4) NOT NULL CHECK (reserved_quantity > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_reservations' AND column_name = 'expires_at'
    ) THEN
        ALTER TABLE inventory_reservations ADD COLUMN expires_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_reservations' AND column_name = 'fulfilled_at'
    ) THEN
        ALTER TABLE inventory_reservations ADD COLUMN fulfilled_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_reservations' AND column_name = 'cancelled_at'
    ) THEN
        ALTER TABLE inventory_reservations ADD COLUMN cancelled_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_reservations' AND column_name = 'notes'
    ) THEN
        ALTER TABLE inventory_reservations ADD COLUMN notes TEXT;
    END IF;
END$$;

-- Create indexes for query performance
CREATE INDEX IF NOT EXISTS idx_reservations_order ON inventory_reservations(order_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status_expires ON inventory_reservations(status, expires_at) WHERE status = 'ACTIVE' AND expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reservations_sku ON inventory_reservations(store_id, sku_id);

-- Add comments for documentation
COMMENT ON TABLE inventory_reservations IS 'Inventory reservation records for pending orders (库存预占记录)';
COMMENT ON COLUMN inventory_reservations.reserved_quantity IS 'Quantity locked for this reservation';
COMMENT ON COLUMN inventory_reservations.status IS 'Reservation state: ACTIVE | FULFILLED | CANCELLED | EXPIRED';
COMMENT ON COLUMN inventory_reservations.expires_at IS 'Auto-release timestamp (NULL = no expiry)';
