/**
 * @spec T003-e2e-runner
 * Integration test for workflow integration with test-scenario-author/e2e-test-generator (T039)
 *
 * This test verifies that e2e-runner can auto-discover and execute tests generated by
 * e2e-test-generator without explicit testMatch configuration.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { loadConfig } from '@/config-loader';
import {
  generatePlaywrightConfig,
  writePlaywrightConfigFile,
  executePlaywrightTests,
} from '@/runner';
import type { E2ERunConfig } from '@/schemas';

const TEST_DIR = join(__dirname, '..', 'fixtures', 'workflow-integration');
const SCENARIOS_DIR = join(TEST_DIR, 'scenarios');
const REPORTS_DIR = join(TEST_DIR, 'reports');

describe('Integration: Workflow with test-scenario-author/e2e-test-generator', () => {
  beforeEach(() => {
    // Clean up test directory
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true, force: true });
    }
    mkdirSync(TEST_DIR, { recursive: true });
    mkdirSync(SCENARIOS_DIR, { recursive: true });
    mkdirSync(REPORTS_DIR, { recursive: true });
  });

  afterEach(() => {
    // Clean up test directory
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true, force: true });
    }
  });

  it('should auto-discover tests in scenarios/ directory without explicit testMatch', () => {
    // Create a simulated generated test file
    const testFilePath = join(SCENARIOS_DIR, 'inventory', 'E2E-INVENTORY-001.spec.ts');
    mkdirSync(join(SCENARIOS_DIR, 'inventory'), { recursive: true });

    const generatedTest = `
/**
 * @spec T002-e2e-test-generator
 * Auto-generated test from scenario: E2E-INVENTORY-001
 */

import { test, expect } from '@playwright/test';

test.describe('Inventory Management', () => {
  test('should load inventory list', async ({ page }) => {
    await page.goto('/inventory');
    await expect(page).toHaveTitle(/Inventory/);
  });

  test('should pass basic assertion', async () => {
    expect(1 + 1).toBe(2);
  });
});
    `;

    writeFileSync(testFilePath, generatedTest);

    // Create config WITHOUT explicit testMatch (should use default)
    const configPath = join(TEST_DIR, 'config.json');
    const config: E2ERunConfig = {
      env_profile: 'test',
      baseURL: 'http://localhost:3000',
      report_output_dir: join(REPORTS_DIR, 'run-1'),
      retries: 0,
      timeout: 30000,
      // Note: testMatch is NOT specified, should default to 'scenarios/**/*.spec.ts'
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Verify testMatch defaults to 'scenarios/**/*.spec.ts'
    expect(loadedConfig.testMatch).toBe('scenarios/**/*.spec.ts');

    // Generate Playwright config
    const playwrightConfig = generatePlaywrightConfig(loadedConfig);

    // Verify testMatch is included in Playwright config
    expect(playwrightConfig.testMatch).toBe('scenarios/**/*.spec.ts');
  });

  it('should respect custom testMatch pattern when specified', () => {
    // Create config WITH explicit testMatch
    const configPath = join(TEST_DIR, 'config-custom.json');
    const config: E2ERunConfig = {
      env_profile: 'test',
      baseURL: 'http://localhost:3000',
      report_output_dir: join(REPORTS_DIR, 'run-2'),
      retries: 0,
      timeout: 30000,
      testMatch: 'tests/e2e/**/*.test.ts', // Custom pattern
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Verify testMatch uses custom value
    expect(loadedConfig.testMatch).toBe('tests/e2e/**/*.test.ts');

    // Generate Playwright config
    const playwrightConfig = generatePlaywrightConfig(loadedConfig);

    // Verify custom testMatch is included in Playwright config
    expect(playwrightConfig.testMatch).toBe('tests/e2e/**/*.test.ts');
  });

  it('should generate Playwright config compatible with e2e-test-generator output', () => {
    // Create a config that mimics real usage
    const configPath = join(TEST_DIR, 'config-realistic.json');
    const config: E2ERunConfig = {
      env_profile: 'saas-staging',
      baseURL: 'https://staging.example.com',
      report_output_dir: join(REPORTS_DIR, 'run-staging'),
      retries: 2,
      workers: 4,
      timeout: 30000,
      // testMatch omitted - should default to scenarios/**/*.spec.ts
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Generate Playwright config
    const playwrightConfig = generatePlaywrightConfig(loadedConfig);

    // Verify all fields are correctly mapped
    expect(playwrightConfig.use?.baseURL).toBe('https://staging.example.com');
    expect(playwrightConfig.retries).toBe(2);
    expect(playwrightConfig.workers).toBe(4);
    expect(playwrightConfig.timeout).toBe(30000);
    expect(playwrightConfig.testMatch).toBe('scenarios/**/*.spec.ts');

    // Verify reporters are configured
    expect(playwrightConfig.reporter).toBeDefined();
    expect(Array.isArray(playwrightConfig.reporter)).toBe(true);
    expect(playwrightConfig.reporter).toHaveLength(3); // json, html, list
  });

  it('should write valid Playwright config file that can be executed', () => {
    const configPath = join(TEST_DIR, 'config-executable.json');
    const config: E2ERunConfig = {
      env_profile: 'test',
      baseURL: 'http://localhost:3000',
      report_output_dir: join(REPORTS_DIR, 'run-executable'),
      retries: 0,
      timeout: 30000,
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Generate Playwright config
    const playwrightConfig = generatePlaywrightConfig(loadedConfig);

    // Write config file
    const tempConfigPath = join(TEST_DIR, 'temp-playwright.config.ts');
    writePlaywrightConfigFile(playwrightConfig, tempConfigPath);

    // Verify file was created
    expect(existsSync(tempConfigPath)).toBe(true);

    // Read and verify content
    const content = require('fs').readFileSync(tempConfigPath, 'utf-8');

    // Should contain proper TypeScript config
    expect(content).toContain('import { defineConfig } from \'@playwright/test\'');
    expect(content).toContain('export default defineConfig');
    expect(content).toContain('@spec T003-e2e-runner');
    expect(content).toContain('http://localhost:3000');
    expect(content).toContain('scenarios/**/*.spec.ts');
  });

  it('should support testdata loading convention from e2e-test-generator', () => {
    // This test verifies that the runner's config doesn't interfere with
    // testdata imports that might be generated by e2e-test-generator

    // Create a test file that simulates testdata import
    const testFilePath = join(SCENARIOS_DIR, 'orders', 'E2E-ORDER-001.spec.ts');
    mkdirSync(join(SCENARIOS_DIR, 'orders'), { recursive: true });

    const generatedTestWithTestData = `
/**
 * @spec T002-e2e-test-generator
 * Auto-generated test with testdata reference
 */

import { test, expect } from '@playwright/test';

// Simulated testdata import (would be generated by e2e-test-generator)
const testData = {
  scenario_id: 'E2E-ORDER-001',
  testdata_ref: 'testdata/orders/order-creation.json',
  variables: {
    customerName: 'Test Customer',
    orderAmount: 100.00
  }
};

test.describe('Order Creation', () => {
  test('should create order with testdata', async ({ page }) => {
    // Test would use testData.variables
    expect(testData.variables.customerName).toBe('Test Customer');
    expect(testData.variables.orderAmount).toBe(100.00);
  });
});
    `;

    writeFileSync(testFilePath, generatedTestWithTestData);

    // Create config
    const configPath = join(TEST_DIR, 'config-testdata.json');
    const config: E2ERunConfig = {
      env_profile: 'test',
      baseURL: 'http://localhost:3000',
      report_output_dir: join(REPORTS_DIR, 'run-testdata'),
      retries: 0,
      timeout: 30000,
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load and generate config
    const loadedConfig = loadConfig(configPath);
    const playwrightConfig = generatePlaywrightConfig(loadedConfig);

    // Verify config doesn't interfere with testdata loading
    expect(playwrightConfig.testMatch).toBe('scenarios/**/*.spec.ts');

    // The test file should be discoverable
    expect(existsSync(testFilePath)).toBe(true);
  });

  it('should handle nested scenario directories correctly', () => {
    // Create nested scenario structure
    const nestedPaths = [
      join(SCENARIOS_DIR, 'inventory', 'queries', 'E2E-INV-QUERY-001.spec.ts'),
      join(SCENARIOS_DIR, 'orders', 'creation', 'E2E-ORD-CREATE-001.spec.ts'),
      join(SCENARIOS_DIR, 'users', 'authentication', 'E2E-USER-AUTH-001.spec.ts'),
    ];

    nestedPaths.forEach((path) => {
      mkdirSync(join(path, '..'), { recursive: true });
      writeFileSync(
        path,
        `
import { test, expect } from '@playwright/test';

test('sample test', async () => {
  expect(true).toBe(true);
});
      `
      );
    });

    // Create config with default testMatch
    const configPath = join(TEST_DIR, 'config-nested.json');
    const config: E2ERunConfig = {
      env_profile: 'test',
      baseURL: 'http://localhost:3000',
      report_output_dir: join(REPORTS_DIR, 'run-nested'),
      retries: 0,
      timeout: 30000,
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Verify default testMatch pattern will match all nested files
    expect(loadedConfig.testMatch).toBe('scenarios/**/*.spec.ts');

    // All test files should exist
    nestedPaths.forEach((path) => {
      expect(existsSync(path)).toBe(true);
    });
  });

  it('should preserve env_profile in workflow for credential matching', () => {
    // Create config with env_profile that would match credentials
    const configPath = join(TEST_DIR, 'config-env-profile.json');
    const config: E2ERunConfig = {
      env_profile: 'saas-staging',
      baseURL: 'https://staging.example.com',
      report_output_dir: join(REPORTS_DIR, 'run-env'),
      credentials_ref: 'credentials/saas-staging.json', // Would match env_profile
      retries: 0,
      timeout: 30000,
    };

    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // Load config
    const loadedConfig = loadConfig(configPath);

    // Verify env_profile is preserved for credentials validation
    expect(loadedConfig.env_profile).toBe('saas-staging');
    expect(loadedConfig.credentials_ref).toBe('credentials/saas-staging.json');

    // Verify testMatch defaults correctly
    expect(loadedConfig.testMatch).toBe('scenarios/**/*.spec.ts');
  });
});
