/**
 * @spec P005-bom-inventory-deduction
 * DeductionRequest DTO
 *
 * Purpose: Request payload for inventory deduction API
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import jakarta.validation.constraints.NotNull;

import java.util.UUID;

/**
 * Deduction Request
 *
 * POST /api/inventory/deductions
 */
public class DeductionRequest {

    @NotNull(message = "Order ID is required")
    private UUID orderId;

    @NotNull(message = "Store ID is required")
    private UUID storeId;

    // Getters and Setters

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }
}
