/**
 * @spec P005-bom-inventory-deduction
 * DeductionResponse DTO
 *
 * Purpose: Response payload for successful inventory deduction
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/**
 * Deduction Response
 *
 * Success response for POST /api/inventory/deductions
 */
public class DeductionResponse {

    private UUID orderId;
    private List<DeductedComponent> deductedComponents;

    public DeductionResponse() {
    }

    public DeductionResponse(UUID orderId, List<DeductedComponent> deductedComponents) {
        this.orderId = orderId;
        this.deductedComponents = deductedComponents;
    }

    // Getters and Setters

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public List<DeductedComponent> getDeductedComponents() {
        return deductedComponents;
    }

    public void setDeductedComponents(List<DeductedComponent> deductedComponents) {
        this.deductedComponents = deductedComponents;
    }

    /**
     * Deducted Component
     */
    public static class DeductedComponent {
        private UUID skuId;
        private String skuName;
        private BigDecimal quantity;
        private String unit;

        public DeductedComponent() {
        }

        public DeductedComponent(UUID skuId, String skuName, BigDecimal quantity, String unit) {
            this.skuId = skuId;
            this.skuName = skuName;
            this.quantity = quantity;
            this.unit = unit;
        }

        // Getters and Setters

        public UUID getSkuId() {
            return skuId;
        }

        public void setSkuId(UUID skuId) {
            this.skuId = skuId;
        }

        public String getSkuName() {
            return skuName;
        }

        public void setSkuName(String skuName) {
            this.skuName = skuName;
        }

        public BigDecimal getQuantity() {
            return quantity;
        }

        public void setQuantity(BigDecimal quantity) {
            this.quantity = quantity;
        }

        public String getUnit() {
            return unit;
        }

        public void setUnit(String unit) {
            this.unit = unit;
        }
    }
}
