/**
 * @spec P005-bom-inventory-deduction
 * InventoryTransactionDTO
 *
 * Purpose: Response DTO for inventory transaction log records
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import com.cinema.inventory.entity.InventoryTransaction;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Inventory Transaction DTO
 *
 * Response format for transaction log queries
 */
public class InventoryTransactionDTO {

    private UUID id;
    private UUID storeId;
    private String storeName;
    private UUID skuId;
    private String skuName;
    private InventoryTransaction.TransactionType transactionType;
    private BigDecimal quantity;
    private BigDecimal quantityBefore;
    private BigDecimal quantityAfter;
    private UUID relatedOrderId;
    private String orderNumber;
    private UUID bomSnapshotId;
    private UUID adjustmentReasonId;
    private String adjustmentReasonName;
    private UUID operatorId;
    private String operatorName;
    private Instant operatedAt;
    private String notes;
    private Instant createdAt;

    // BOM components (for detail view)
    private List<BomComponentDTO> bomComponents;

    // Constructors

    public InventoryTransactionDTO() {
    }

    // Getters and Setters

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public String getSkuName() {
        return skuName;
    }

    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    public InventoryTransaction.TransactionType getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(InventoryTransaction.TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getQuantityBefore() {
        return quantityBefore;
    }

    public void setQuantityBefore(BigDecimal quantityBefore) {
        this.quantityBefore = quantityBefore;
    }

    public BigDecimal getQuantityAfter() {
        return quantityAfter;
    }

    public void setQuantityAfter(BigDecimal quantityAfter) {
        this.quantityAfter = quantityAfter;
    }

    public UUID getRelatedOrderId() {
        return relatedOrderId;
    }

    public void setRelatedOrderId(UUID relatedOrderId) {
        this.relatedOrderId = relatedOrderId;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public UUID getBomSnapshotId() {
        return bomSnapshotId;
    }

    public void setBomSnapshotId(UUID bomSnapshotId) {
        this.bomSnapshotId = bomSnapshotId;
    }

    public UUID getAdjustmentReasonId() {
        return adjustmentReasonId;
    }

    public void setAdjustmentReasonId(UUID adjustmentReasonId) {
        this.adjustmentReasonId = adjustmentReasonId;
    }

    public String getAdjustmentReasonName() {
        return adjustmentReasonName;
    }

    public void setAdjustmentReasonName(String adjustmentReasonName) {
        this.adjustmentReasonName = adjustmentReasonName;
    }

    public UUID getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(UUID operatorId) {
        this.operatorId = operatorId;
    }

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public Instant getOperatedAt() {
        return operatedAt;
    }

    public void setOperatedAt(Instant operatedAt) {
        this.operatedAt = operatedAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public List<BomComponentDTO> getBomComponents() {
        return bomComponents;
    }

    public void setBomComponents(List<BomComponentDTO> bomComponents) {
        this.bomComponents = bomComponents;
    }

    /**
     * BOM Component DTO
     *
     * Represents a single component from BOM snapshot
     */
    public static class BomComponentDTO {
        private UUID componentSkuId;
        private String componentSkuName;
        private BigDecimal standardQuantity;
        private BigDecimal wastageRate;
        private BigDecimal actualQuantity; // standardQuantity * (1 + wastageRate)
        private String unit;
        private BigDecimal unitCost;
        private Boolean isOptional;

        // Getters and Setters

        public UUID getComponentSkuId() {
            return componentSkuId;
        }

        public void setComponentSkuId(UUID componentSkuId) {
            this.componentSkuId = componentSkuId;
        }

        public String getComponentSkuName() {
            return componentSkuName;
        }

        public void setComponentSkuName(String componentSkuName) {
            this.componentSkuName = componentSkuName;
        }

        public BigDecimal getStandardQuantity() {
            return standardQuantity;
        }

        public void setStandardQuantity(BigDecimal standardQuantity) {
            this.standardQuantity = standardQuantity;
        }

        public BigDecimal getWastageRate() {
            return wastageRate;
        }

        public void setWastageRate(BigDecimal wastageRate) {
            this.wastageRate = wastageRate;
        }

        public BigDecimal getActualQuantity() {
            return actualQuantity;
        }

        public void setActualQuantity(BigDecimal actualQuantity) {
            this.actualQuantity = actualQuantity;
        }

        public String getUnit() {
            return unit;
        }

        public void setUnit(String unit) {
            this.unit = unit;
        }

        public BigDecimal getUnitCost() {
            return unitCost;
        }

        public void setUnitCost(BigDecimal unitCost) {
            this.unitCost = unitCost;
        }

        public Boolean getIsOptional() {
            return isOptional;
        }

        public void setIsOptional(Boolean isOptional) {
            this.isOptional = isOptional;
        }
    }
}
