/**
 * @spec P005-bom-inventory-deduction
 * MaterialRequirement DTO
 *
 * Purpose: Data transfer object for BOM expansion results
 * Represents the raw material quantity required for a specific SKU
 *
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Material Requirement
 *
 * Represents a raw material or packaging component needed for a finished product.
 * Used as the output of BOM expansion.
 */
public class MaterialRequirement {

    /**
     * Raw material SKU ID
     */
    private UUID skuId;

    /**
     * Raw material SKU name (for display/logging)
     */
    private String skuName;

    /**
     * Required quantity
     * Formula: standard_quantity * (1 + wastage_rate)
     */
    private BigDecimal quantity;

    /**
     * Unit of measurement
     */
    private String unit;

    /**
     * Standard quantity defined in BOM (before wastage)
     */
    private BigDecimal standardQuantity;

    /**
     * Wastage rate applied (0.0 to 1.0)
     */
    private BigDecimal wastageRate;

    public MaterialRequirement() {
    }

    public MaterialRequirement(UUID skuId, String skuName, BigDecimal quantity, String unit) {
        this.skuId = skuId;
        this.skuName = skuName;
        this.quantity = quantity;
        this.unit = unit;
        this.standardQuantity = quantity;
        this.wastageRate = BigDecimal.ZERO;
    }

    public MaterialRequirement(UUID skuId, String skuName, BigDecimal quantity, String unit, BigDecimal standardQuantity, BigDecimal wastageRate) {
        this.skuId = skuId;
        this.skuName = skuName;
        this.quantity = quantity;
        this.unit = unit;
        this.standardQuantity = standardQuantity;
        this.wastageRate = wastageRate;
    }

    // Getters and Setters

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public String getSkuName() {
        return skuName;
    }

    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public BigDecimal getStandardQuantity() {
        return standardQuantity;
    }

    public void setStandardQuantity(BigDecimal standardQuantity) {
        this.standardQuantity = standardQuantity;
    }

    public BigDecimal getWastageRate() {
        return wastageRate;
    }

    public void setWastageRate(BigDecimal wastageRate) {
        this.wastageRate = wastageRate;
    }

    @Override
    public String toString() {
        return "MaterialRequirement{" +
                "skuId=" + skuId +
                ", skuName='" + skuName + '\'' +
                ", quantity=" + quantity +
                ", unit='" + unit + '\'' +
                '}';
    }
}
