/**
 * @spec P005-bom-inventory-deduction
 * ReservationResponse DTO
 *
 * Purpose: Response payload for successful inventory reservation
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/**
 * Reservation Response
 *
 * Success response for POST /api/inventory/reservations
 */
public class ReservationResponse {

    private UUID orderId;
    private List<UUID> reservationIds;
    private List<ReservedComponent> reservedComponents;

    public ReservationResponse() {
    }

    public ReservationResponse(UUID orderId, List<UUID> reservationIds, List<ReservedComponent> reservedComponents) {
        this.orderId = orderId;
        this.reservationIds = reservationIds;
        this.reservedComponents = reservedComponents;
    }

    // Getters and Setters

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public List<UUID> getReservationIds() {
        return reservationIds;
    }

    public void setReservationIds(List<UUID> reservationIds) {
        this.reservationIds = reservationIds;
    }

    public List<ReservedComponent> getReservedComponents() {
        return reservedComponents;
    }

    public void setReservedComponents(List<ReservedComponent> reservedComponents) {
        this.reservedComponents = reservedComponents;
    }

    /**
     * Reserved Component
     */
    public static class ReservedComponent {
        private UUID skuId;
        private String skuName;
        private BigDecimal quantity;
        private String unit;

        public ReservedComponent() {
        }

        public ReservedComponent(UUID skuId, String skuName, BigDecimal quantity, String unit) {
            this.skuId = skuId;
            this.skuName = skuName;
            this.quantity = quantity;
            this.unit = unit;
        }

        // Getters and Setters

        public UUID getSkuId() {
            return skuId;
        }

        public void setSkuId(UUID skuId) {
            this.skuId = skuId;
        }

        public String getSkuName() {
            return skuName;
        }

        public void setSkuName(String skuName) {
            this.skuName = skuName;
        }

        public BigDecimal getQuantity() {
            return quantity;
        }

        public void setQuantity(BigDecimal quantity) {
            this.quantity = quantity;
        }

        public String getUnit() {
            return unit;
        }

        public void setUnit(String unit) {
            this.unit = unit;
        }
    }
}
