/**
 * @spec P005-bom-inventory-deduction
 * ReservationRequest DTO
 *
 * Purpose: Request payload for inventory reservation API
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/**
 * Reservation Request
 *
 * POST /api/inventory/reservations
 */
public class ReservationRequest {

    @NotNull(message = "Order ID is required")
    private UUID orderId;

    @NotNull(message = "Store ID is required")
    private UUID storeId;

    @NotEmpty(message = "Items list cannot be empty")
    @Valid
    private List<OrderItem> items;

    // Getters and Setters

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }

    /**
     * Order Item
     */
    public static class OrderItem {

        @NotNull(message = "SKU ID is required")
        private UUID skuId;

        @NotNull(message = "Quantity is required")
        @Positive(message = "Quantity must be positive")
        private BigDecimal quantity;

        @NotNull(message = "Unit is required")
        private String unit;

        // Getters and Setters

        public UUID getSkuId() {
            return skuId;
        }

        public void setSkuId(UUID skuId) {
            this.skuId = skuId;
        }

        public BigDecimal getQuantity() {
            return quantity;
        }

        public void setQuantity(BigDecimal quantity) {
            this.quantity = quantity;
        }

        public String getUnit() {
            return unit;
        }

        public void setUnit(String unit) {
            this.unit = unit;
        }
    }
}
