/**
 * @spec P005-bom-inventory-deduction
 * TransactionQueryRequest DTO
 *
 * Purpose: Request payload for querying inventory transaction logs
 * Author: Generated by P005 spec
 * Date: 2025-12-29
 */

package com.cinema.inventory.dto;

import com.cinema.inventory.entity.InventoryTransaction;

import java.time.Instant;
import java.util.UUID;

/**
 * Transaction Query Request
 *
 * GET /api/inventory/transactions
 *
 * Supports filtering by:
 * - Transaction type (BOM_DEDUCTION, RESERVATION_RELEASE, etc.)
 * - SKU ID
 * - Date range (startDate, endDate)
 * - Order ID
 * - Store ID
 *
 * Supports pagination via page and pageSize
 */
public class TransactionQueryRequest {

    private InventoryTransaction.TransactionType transactionType;
    private UUID skuId;
    private UUID orderId;
    private UUID storeId;
    private Instant startDate;
    private Instant endDate;

    // Pagination
    private Integer page = 0;
    private Integer pageSize = 20;

    // Sorting
    private String sortBy = "operatedAt";
    private String sortDirection = "DESC";

    // Getters and Setters

    public InventoryTransaction.TransactionType getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(InventoryTransaction.TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    public UUID getSkuId() {
        return skuId;
    }

    public void setSkuId(UUID skuId) {
        this.skuId = skuId;
    }

    public UUID getOrderId() {
        return orderId;
    }

    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public Instant getStartDate() {
        return startDate;
    }

    public void setStartDate(Instant startDate) {
        this.startDate = startDate;
    }

    public Instant getEndDate() {
        return endDate;
    }

    public void setEndDate(Instant endDate) {
        this.endDate = endDate;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public String getSortBy() {
        return sortBy;
    }

    public void setSortBy(String sortBy) {
        this.sortBy = sortBy;
    }

    public String getSortDirection() {
        return sortDirection;
    }

    public void setSortDirection(String sortDirection) {
        this.sortDirection = sortDirection;
    }
}
